### ISSUE TITLE
결제시 대여자에게 기증자 내역을 보여줄 화면 구성 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#102]
금일부터는 모든 기증자를 모두 알려주고 모든 기증자를 대상으로 메세지를 작성하도록 요청하려고 합니다. 때문에 이를 위해 결제시 주문서를 보여주는 것보다는 대여자가 보는 반대편의 독립된 모니터에서 품목별 기증자를 알려주고 싶습니다. 이때 예상 반납일과 결제시 필요한 공지 내용을 함께 안내하고 싶습니다.

**Comment by aanoaa** [comment]
어떤 내용이 들어가야할지 정리해주세요.

+ 대기자 현황판에 안내/광고성 내용이 추가됨으로 해결 될 수도 있을 것 같습니다.

**Comment by aanoaa** [comment]
아직 해결방안이 생각나지 않는다고 하므로 닫겠습니다.
