### ISSUE TITLE
방문시 대여자가 직접 방문을 누르도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#103]
5층의 프로세스를 살펴본 결과 안내에 너무 많은 에너지가 소비된다고 판단하였습니다.
그래서 기존에 안내/결제를 포장/결제로 바꾸고 안내 대신 고객이 방문했을 때 자신의 예약 현황판에서 쉽게 방문으로 누르고 들어 올 수 있도록 변경하고자 합니다. 예약을 하지 않은 경우에는 저희를 호출 할 수 있도록 하여 예외적인 상황을 대비하고 싶습니다. 이 부분에 대해서는 추가 논의 필요할 것으로 보입니다. 방문해서 다시 말씀드리도록 하겠습니다.

**Comment by aanoaa** [comment]
이거는 확실해지면 다시 말씀해주세요.

**Comment by 10001if** [comment]
@aanoaa 네~! 알겠습니다. ^^
