### ISSUE TITLE
빈 탈의실을 '사용중' 상태로 변경할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#112]
![2016-05-10 11 45 05](https://cloud.githubusercontent.com/assets/4696328/15134291/b6a9a434-16a5-11e6-8c79-1c98e838ab9b.png)
의류를 바로 입고 가야 하는 사용자가 존재할 경우, 본 사용자는 탈의실을 이미 빠져나온 상태이므로 탈의실이 사용 중인지 여부를 표시할 수가 없고 때문에 탈의실이 사용 중인지 여부를 알 수가 없습니다. 위의 그림처럼 빈 탈의실일 경우 사용중을 표시할 수 있도록 기능이 추가되었으면 합니다. 물론 사용중 표시를 없애는 기능도 필요합니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/814

**Comment by aanoaa** [comment]
입고가는사람의 절차

- 탈의
- 포장대에 전달
- 다시 탈의실 사용
- <- 이때 포장후에 탈의실을 사용할 수가 없음

이런문제가 해결되어야 합니다.

**Comment by aanoaa** [comment]
사용되고 있진 않지만, 탈의실도 마우스로 클릭해서 active 상태를 껏다
켯다 할 수 있습니다.

하지만 비어있는 탈의실에 대해서는 동작하지 않습니다.

비어있는 탈의실에도 적용하던지 다른 방법을 알아보던지 하겠습니다.

**Comment by aanoaa** [comment]
입고가시는 분이 언제 탈의실을 나가나요?
포장완료후에 탈의실에서 옷을 입고 다입으면 바로 결제장소로 가는건가요?

탈의실을 눌러서 상태를 추가하는 것이라면
탈의실 이용후에 정리버튼을 안누르는 것으로 대체할 수 있지않나요?

입고가시는분이 탈의실에서 나간 후 상태변경에 따라 자동으로 탈의실을 사용할 수 있도록 할 수 있으면 좋을 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 저도 보라색으로 변하는 기능을 생각하였습니다. 하지만 이야기 주신 것처럼 탈의실이 비어 있을 때는 작동하지 않고 있습니다~ 

입고 가시는 분이 탈의실을 나가는 시점은 조금씩 다릅니다.

1번 경우 
1) 의류 착용 후 의류를 결정
2) 착용한 의류를 벗어 포장대로 가져감
3) 포장완료 후 다시 탈의실에서 의류를 착용
4) 결제

2번 경우
1) 의류 착용 후 의류를 결정
2) 착용한 의류를 벗어 포장대로 가져감
3) 포장완료 후 결제를 마침
4) 착용의류로 갈아입고 나감

대여자가 많지 않을 때에는 탈의실을 오랫동안 점유하고 있어도 관계가 없지만,
요즘처럼 탈의실이 부족한 경우에는 포장완료, 결제를 기다리는 동안 탈의실을 사용할 수 없게 되어서
탈의실이 부족한 상황이 발생합니다. 

그리고 포장 상태로 변경이 되면 탈의실 화면에 정리 표시가 뜨기 때문에 안쪽의 의류를 고르는 직원분들은 탈의실을 정리하게 됩니다. 제가 질문에 제대로 된 답을 한 건지 모르겠는데, 오시면 다시 말씀드리겠습니다. ^^

**Comment by aanoaa** [comment]
입고가시는분이 어떤 상태로 변경되는 시점에 탈의실을 사용가능하게끔 하는 방안을 말씀드렸습니다.
이와 관련해서 내부 의견을 들어보고 답변해주시기로 했습니다.

**Comment by 10001if** [comment]
@aanoaa 적절한 방안을 고려 중입니다. 다만, 반드시 프로그램이 개선되어야 하는 문제인지 체크하기 위해 내부적으로 몇 가지 실험을 진행 중입니다. 결과가 나오면 공유드리겠씁니다.

**Comment by aanoaa** [comment]
탈의 -> 포장 -> 탈의 -> 결제대기 -> bye

사용자의 상태가 그대로 반영되도록 하는 것이 좋을 것 같습니다.
그렇게 하기 위해서는,

- 포장상태에서 비어있는 탈의실로 상태를 변경합니다.
- 옷을 다 갈아입었으면, 결제하로 이동합니다.
  - 주문서의 `포장완료` 목록에서는 입고가면서 탈의실 상태인 주문서도 함께 보여줘야 합니다.

**Comment by aanoaa** [comment]
@10001if 바로 위에 코멘트의 내용이 맞는지 확인바랍니다.

**Comment by aanoaa** [comment]
현재는 1번 탈의실을 입고가시는분 전용(?)으로 사용중입니다(모자르면 2번 탈의실도 이용)
의견을 여쭈어봤는데 별 어려움은 없다고 합니다.

**Comment by 10001if** [comment]
@aanoaa 코멘트 적어주신 내용이 맞습니다~ ^^

**Comment by aanoaa** [comment]
아까 안계셔서 어떻게 해야할지 확인차 5층에서 이것저것 물어봤는데,
지금 사용하는데 별 어려움이 없다고 했는데 계속해서 진행하나요?

**Comment by aanoaa** [comment]
@10001if 이 기능은 필요가 없을 것 같은데 진행하나요?

**Comment by 10001if** [comment]
@aanoaa 네! 필요합니다. 별 어려움이 없다는 의견은 조금 사실과 다른 것 같습니다. ^^

**Comment by aanoaa** [comment]
> 사용자의 상태가 그대로 반영되도록 하는 것이 좋을 것 같습니다.

이렇게 된다면 좋을 것 같지만 현실적인 어려움이 있습니다.
대여중인 주문서를 다시 탈의로 넣는다는게 좀..

현재 사용하는 포스트잇을 대체하는 용도로 비어있는 탈의실에 대해 상태를 추가하도록 하겠습니다.

빈탈의실이지만 사용중인 상태
레알 빈탈의실..

....

**Comment by 10001if** [comment]
@aanoaa 진행해 주시면 됩니다. ^^
