### ISSUE TITLE
의류준비 화면구성 수정 공통 사항

### ISSUE THREAD

**Issue by yongbin** [opencloset/monitor#114]
#94 

![cb91ecde-29ac-11e6-93a7-ce32a6221f6c](https://cloud.githubusercontent.com/assets/52704/15773838/483d60d6-29b4-11e6-97c6-c79875fff0a8.png)

1. [ ] 영역과 글자크기를 현재 대비 20% 정도 줄여주세요 
2. [ ] `허벅지(녹색)`과 `허리(회색)` 을 `허리(녹색)` 과 `허벅지(회색)` 으로 변경해주세요
3. [ ] 모든경우에 예상 사이즈를 표시하므로 3번 영역에 다음 정보를 표시합니다.(OpenCloset::Size::Guess를 통해 OpenCPU::RandomForest 에 질의보내서 결과로 받은 결과값을 소숫점 첫째자리에서 반올림한 값 - 남자,여자 항목다름)
  - 가슴 115
  - 윗배 110
  - 팔 63
  - 허리 100
  - 허벅지 74
4. [ ] 사용자 이름 옆에 괄호와 함께 이 사람의 총 대여횟수를 표시해주세요 즉 이 경우 유용빈(4) 입니다.

**Comment by aanoaa** [comment]
여성의류는 제안해주지 않나요?

**Comment by aanoaa** [comment]
>질의보내서 결과로 받은 결과값

이게 뭔가요?
대여이력에서의 평균값인가요?

**Comment by aanoaa** [comment]
본래이슈에서 진행하겠습니다.
정리해주신 내용은 참고하겠습니다.

**Comment by yongbin** [comment]
> 여성의류는 제안해주지 않나요?

정확하게 이야기하면 이야기하면 여성의 사이즈는 예측을 하지만 여자 옷들이 대부분 세트 등록이 되어있지 않기때문에 검색결과가 거의 안나오는 상황입니다. 

> 이게 뭔가요?
> 대여이력에서의 평균값인가요?

`randomForest`(https://en.wikipedia.org/wiki/Random_forest)  라는 알고리즘을 통해서 과거 대여기록을 학습시킨 결과로 부터 얻어낸 예측 결과입니다. 랜덤포레스트는 분류나 회귀 문제를 해결할때 의사결정나무를 무수히 많이 만들어서 그중에 일부만 취해서 결과값에 정확도를 높히는 알고리즘 입니다. 크게는 의사결정나무(https://en.wikipedia.org/wiki/Decision_tree) 에 베깅(https://en.wikipedia.org/wiki/Bootstrap_aggregating)과 부스팅(https://en.wikipedia.org/wiki/Boosting_%28machine_learning%29)이 결합된 형태라고 보시면 됩니다. 우리가 쓰는건 분류문제(맞다 틀리다)가 아니라 회귀문제(치수니까)이기때문에 아래 링크에 내용이 잘 정리되어있습니다.

https://www.quora.com/How-does-random-forest-work-for-regression-1

**Comment by aanoaa** [comment]
입력된 신체사이즈에 대해 예측된 신체사이즈인가요?

**Comment by yongbin** [comment]
> 입력된 신체사이즈에 대해 예측된 신체사이즈인가요?

입력된 신체사이즈에 대한 예측된 **의류사이즈** 입니다
