### ISSUE TITLE
세트를 대여하고 과거 대여이력이 있는 경우 의류준비 항목

### ISSUE THREAD

**Issue by yongbin** [opencloset/monitor#115]
#94 

- #114 가 모두 반영되어야 합니다.
- 세트를 대여 한다는 의미는 `user_info`.`pre_category` 에 `상의`, `하의`가 포함된 경우를 말합니다. 
- 과거 대여이력이 있다는 의미는 `order` 에 해당 user_id로 대여기록이 있다는걸 의미합니다.

![case1 copy 2](https://cloud.githubusercontent.com/assets/52704/15772820/5129b3da-29ae-11e6-9d73-0668fa39ffd9.png)

이런 경우 입니다.

**Comment by yongbin** [comment]
![case-common-rented](https://cloud.githubusercontent.com/assets/52704/15773058/d214b25a-29af-11e6-98d8-3abc18bf2567.png)

# 1 
-  [ ] 공통으로 적용되는 사항입니다. 대여기록항목은 아래와 같은 형식으로 표시됩니다.
   - 대여날짜
   - 상의(코드 - 사이즈) - 마우스 hover시 의류의 바코드 번호 표시 
   - 하의(코드 - 사이즈) - 마우스 hover시 의류의 바코드 번호 표시 
   - 색상 (현재는 없지만 추가되어야 합니다 '검쟁', '브라운' 등의 색상표기입니다. 세트의 경우 색상이 동일하기때문에 하나만 표시합니다 ) 
-  [ ] 다음은 제거하거 수정합니다.
    - '재킷', '바지' 등의텍스트 제거
    - 현재 재킷 바지의 정렬순서가 서로 다른데 재킷, 바지로 표시 순서 고정
    - 항목별 맨 앞에 `O` 문자 제거

# 2
 - [ ] 과거 대여항목 표시에서 상의와 하의를 제외한 의류는 앞으로 표시하지 않습니다. 즉 현재 목록에서 다음 항목은 모두 삭제 됩니다.
   - S193 셔츠 95
   - S18U 셔츠 95
   - S006 셔츠 96
   -  S072 셔츠 94
   - T0MB 넥타이 

# 3

- [ ] 상의와 하의중 하나라도 대여가능 상태가 아닌경우 목록에 표시하지 않습니다. 즉 이 화면에서 2014-12-20 대여기록을 표시될 필요가 없습니다.

**Comment by yongbin** [comment]
![case1_copy_3](https://cloud.githubusercontent.com/assets/52704/15773442/d85081d8-29b1-11e6-9e62-97721f3b2f3d.png)

# 1

 - 10개(설정가능항목)에서 과거 대여기록 표시 수 (이 경우 3개) 를 뺀 나머지 자리 (이 경우 7개)에 과거 대여기록과 동일한 형식으로 검색 추천 의류를 표시합니다.
  - 공란 (대여기록날짜가 없으므로 첫줄은 공란입니다)
  - 상의 코드 - 사이즈 / 마우스 hover시 바코드 번호 
  - 하의 코드 - 사이즈 / 마우스 hover시 바코드 번호 
  - 색상

# 2

이때 정렬은 다음과 같은 규칙으로 합니다.

 1. 사용자의 **첫번째** 선호색상 (`user_info`.`pre_color`) 
 2. 대여횟수 역순

즉 사진의 경우 `검정` 이므로 검색결과의 정렬규칙은 다음과 같습니다.

 1. 검색결과 색상이 검정인경우 목록을 대여횟수로 역순정렬
 2. 남은 목록은 대여횟수 역순 정렬

좀 더 구체적으로 예를 들면 

![screen_shot_2016-06-03_at_2_46_39_pm](https://cloud.githubusercontent.com/assets/52704/15773587/ae576f26-29b2-11e6-8554-a435f1c4ceaf.png)

와 같은 의류검색 결과가 있고 사용자의 선호 색상이 `블랙` 이었다면 

 1. 24건 대여된 블랙
 1. 22건 대여된 블랙
 1. 22건 대여된 블랙
 1. 13건 대여된 블랙
 1. 67건 대여된 네이비
 1. 27건 대여된 브라운
 1. 22건 대여된 차콜 그레이 
 1. 7건 대여된 네이비 
 1. 3건 대여된 그레이 


이런 순서로 정렬되어야 합니다. 만약 이 결과가 위 화면에 표시된다면  7건에서 잘리게 되므로 뒤에 두항목(7건 대여된 네이비와 3건 대여된 그레이)는 화면에 표시되지 않습니다.

**Comment by aanoaa** [comment]
> 상의 코드 - 사이즈 / 마우스 hover시 바코드 번호

바코드 번호가 뭔가요?

**Comment by aanoaa** [comment]
본래이슈에서 진행하겠습니다.
정리해주신 내용은 참고하겠습니다.

**Comment by yongbin** [comment]
> 바코드 번호가 뭔가요?

기존의 의류코드를 정렬가능한 10진코드로 만든결과 입니다. https://barcode.theopencloset.net/ 를 통해 구해와도 되고 단순하게 다음 코드로 구할 수 있습니다.

```perl
my $barcode = sub {
  my $code = substr($_[0],1) if substr($_[0], 0,1) eq 0;
  my @barcode = map { $encode{$_} } split(//, $code);
  return $barcode[0] . $barcode[1] . '-' . $barcode[2] . $barcode[3];
};

say $barcode->($upper_rs->code);

```

**Comment by aanoaa** [comment]
`J001` 이면 `1900 - 0001` 입니다.
`1900 - 0001` 이 바코드번호입니다.
