### ISSUE TITLE
세트를 대여하고 과거 대여이력이 없는 경우 의류준비 항목

### ISSUE THREAD

**Issue by yongbin** [opencloset/monitor#116]
#94 

- #114 가 모두 반영되어야 합니다.

![screen_shot_2016-06-03_at_2_26_00_pm_copy](https://cloud.githubusercontent.com/assets/52704/15773746/b17cfe40-29b3-11e6-9762-5f3667c5b021.png)

# 1

 #115 와 완전 동일합니다. 대신 화면에 표시하는 추천의류의 수가 설정된 표시수 (현재 기준 10건)이 되어야 합니다.

**Comment by aanoaa** [comment]
본래이슈에서 진행하겠습니다.
정리해주신 내용은 참고하겠습니다.
