### ISSUE TITLE
단품을 대여하는 경우 의류준비 항목

### ISSUE THREAD

**Issue by yongbin** [opencloset/monitor#117]
#94 

-  #114 가 모두 반영되어야 합니다.
- 단품을 대여하는 경우란 `user_info`.`pre_category` 에 성별별 상하의가 포함되지 않은 경우를 의미합니다.
- 단품을 대여하는 경우는 의류추천을 하지 않습니다.

![screen_shot_2016-06-03_at_2_35_50_pm_copy](https://cloud.githubusercontent.com/assets/52704/15774012/14c91dd4-29b5-11e6-997c-77f1c637d680.png)

# 1

 - 과거 의류대여 기록에서 악세사리(상하의가 아닌 항목)은 모두 표시하지 않습니다.
 - 과거 의류대여기록에서 **대여가능** 한 상의 단품대여기록만 보여줍니다. 이때 과거 대여한 세트 대여기록이 있어도 보여주지 않습니다.

**Comment by aanoaa** [comment]
본래이슈에서 진행하겠습니다.
정리해주신 내용은 참고하겠습니다.
