### ISSUE TITLE
대여목록의 수선된 주문서의 상태표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#122]
https://github.com/opencloset/opencloset/issues/816

staff 와 관련이 있는 이슈입니다.
수선된 이력이 있는 주문서는 이력을 남겨놓을 필요가 있습니다.
수선 목록이 비워질때마다 캐시를 비우기 때문에
staff 의 대여화면에서 수선을 거친 주문서가 표시가 안될 수 있습니다.

**Comment by yongbin** [comment]
`order_status_log`를 이용하면 의류에 수선된 이력을 확인할 수 있습니다.

**Comment by aanoaa** [comment]
수선절차입니다.

- 대여자가 수선으로 상태가 변경되고 의류를 수선합니다.
- /repair 에서 의류수선이 완료가 되면 수선이 완료된 체크박스를 누릅니다.
  이때에, 수선완료된 주문서의 번호가 저장됩니다.

        redis> keys *
        1) "opencloset:storage"
        2) "opencloset:storage:repair"    <- 이게 수선완료된 주문서목록을 가지고 잇는 key
        3) "opencloset:storage:clothes"
        redis> hgetall opencloset:storage:repair
        1) "31917"    <- 이게 주문서번호
        2) "1"

- 수선 -> 포장으로 변경합니다.

수선완료된 주문서목록은 수선중이 주문서가 없을때 비워지게 됩니다.
문제가 생기는 것이 이때입니다.

- 수선 -> 포장으로 변경
- 수선중인 주문서가 한개도 없음
- 어떤 주문서가 수선되엇었는지 모름

**Comment by aanoaa** [comment]
해결책으로는,
수선완료된 주문서목록을 수선중인 주문서가 없을때 비워지는 것이 아니라
수선중인 주문서와 포장중인 주문서가 없을때 비워지게 하면 될 것 같습니다.
