### ISSUE TITLE
의류검색시 추천의류의 나타나는 스커트 사이즈 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#124]
스커트 사이즈가 현재는 허리가 뜨고 있습니다.

-> 엉덩이, 허리 순으로 변경 요청드립니다. 기존 의류를 보여주는 화면에서는 이렇게 보여지고 있습니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/878

**Comment by aanoaa** [comment]
스커트는 추천되고 있지 않은데..

**Comment by aanoaa** [comment]
제가 잘못 알았습니다.
여성의류의 경우에도 추천의류가 검색됩니다.
