### ISSUE TITLE
검색결과 정렬방식 개선

### ISSUE THREAD

**Issue by yongbin** [opencloset/monitor#125]
https://github.com/opencloset/opencloset/issues/867 과 대응하는 모니터 이슈입니다.

**Comment by yongbin** [comment]
RSS를 화면에 어떻게 표현할지에 대해서는 결정되지 않았기 때문에  https://github.com/opencloset/opencloset/issues/867 에 변경사항을 단순하게 반영한 PR을 보냈습니다. 표시되는 수치가 `rent_count`에서 `rss`로 변경된것 이외에 정렬순서역시 변경이 반영되어있습니다.

![screen_shot_2016-07-06_at_7_54_52_pm](https://cloud.githubusercontent.com/assets/52704/16616153/5a8c0e1a-43b6-11e6-999b-51f9d17c521c.png)

**Comment by yongbin** [comment]
피드백 받았습니다. 현재 안 대로 진행합니다.

**Comment by aanoaa** [comment]
rss 가 무슨 뭔가요? 약자인가요?

**Comment by yongbin** [comment]
Residual sum of squares의 약자입니다. 의미는 예측값에서 실제값을 뺀 차이를 제곱한 뒤에 합한값이고 한국말로는 `잔차 제곱 합` 이라고 합니다. staff에서는 간단하게 '오차'라고 부르기로 했습니다. 

https://github.com/opencloset/opencloset/pull/883/commits/f5634c3697c61eee2c0053c43d66573c13854b34

https://en.wikipedia.org/wiki/Residual_sum_of_squares

**Comment by yongbin** [comment]
결과화면 확인와료했고 머지했습니다. 이슈 닫습니다.
