### ISSUE TITLE
의류준비탭에서 사용자 화면 바로가기

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#129]
사용자의 이름을 누르면 bestfit toggle 기능입니다.
우클릭 메뉴에 사용자화면으로 바로갈 수 있는 메뉴가 추가되어야 합니다.

비슷하게 제안된 의류 혹은 대여했던 의류역시 바로가기가 필요합니다.
베스트핏 이런거 없으니까 누르면 그냥 이동하면 될 것 같습니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/984

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2016-11-22 17-21-29](https://cloud.githubusercontent.com/assets/170528/20516107/2e0ec9ce-b0d8-11e6-9324-62628dd54b4e.png)


우클릭 메뉴 대신에 나이 옆에 링크 아이콘을 넣었습니다.
