### ISSUE TITLE
의류준비탭 지난 대여이력에 마우스 오버(hover)

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#144]
추천의류와 마찬가지로 의류태그를 볼 수 있었으면 합니다.

**Comment by 10001if** [comment]
본 기능이 제공되지 않아 의류를 찾는데 불편함이 많이 있다는 제보입니다. 빠른적용 요청드립니다. ^^

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1177
