### ISSUE TITLE
~/online 이 접속되지 않음 

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#146]
~/online 이 접속 되지 않고 있습니다. 확인 부탁드립니다.
![2017-02-02 10 31 04](https://cloud.githubusercontent.com/assets/4696328/22534049/e9d0f4ae-e934-11e6-8265-83a6b710a0f8.png)

**Comment by aanoaa** [comment]
[Thu Feb  2 11:00:06 2017] [error] Can't call method "date" on an undefined value at template dashboard/online.html.ep line 109.

온라인 주문서에는 booking date 가 없어서 발생하는 문제가 아닌가 싶습니다.
