### ISSUE TITLE
예약확인을 별도의 모니터에서 무인으로 실시함

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#148]
현재 예약확인 시스템은 대여탭(~/rental/2017-04-06)에서 진행됩니다.
![2017-04-06 2 39 00](https://cloud.githubusercontent.com/assets/4696328/24739457/0e9db366-1ad7-11e7-9a5c-4e355710a816.png)

아래와 같은 화면으로 작동하는데요.

본 기능은 대부분 자원 봉사자분께서 진행해 주고 계십니다. 자원봉사자는 포장과 대여를 동시에 진행하는데요. 현재 구조상 입구에서 인원을 맞이해야 하기 때문에 그렇게 진행하고 있습니다. 하지만 포장과 예약확인이 동시에 진행됨에 따라 발생하는 문제들이 반복적으로 일어나고 있습니다.

더불어, 5월 부터는 더 넓은 공간에서 대여를 진행하려고 하는데요. 그렇게 되면 포장, 결제, 예약확인을 같이 붙여넣지 않아도 가능합니다. 따라서 예약확인은 무인으로 직접 할 수 있도록 진행하려고 합니다.

요청사항은 다음과 같습니다.

기본적인 요청사항은 대여탭에 있는 내용과 크게 다르지 않습니다. 다만, 철저히 무인으로 진행될 것이어서 조금 더 쉽게 바꾸고자 합니다.

1.  예약여부 확인
예약하셨나요?  예약했습니다. | 예약하지 않았습니다.

2-1. 예약했습니다.
전화번호 뒷자리를 눌러주세요. or 이름을 입력해주세요.
누르면 현재 보이는 화면처럼 나타나서 이름을 클릭할 수 있도록 함.
다만, 다른사람의 정보를 함께 볼 수 있으므로 이메일, 전화번호의 중간자리는 보이지 않도록 함.

2-2. 예약하지 않았습니다.
전화번호를 입력해주세요. 문자로 예약이 가능한 URL을 전송해 드리겠습니다.
URL을 클릭하여 현장에서 예약해주세요. 현장 예약자 식별이 가능하다면, 그 예약자는 별도의 방문 클릭 없이 예약과 동시에 방문으로 상태 변경이 되도록 하고 싶습니다. 그게 어렵다면, 추가 안내가 필요합니다.

예약 후 현재 자리에서 방문 확인 해주세요.

3. 방문 확인 완료
000님 2017-00-00 00시 00분예 예약하신 방문 확인이 완료되었습니다. 대기실에 앉아 신체치수 측정을 기다려 주세요. 문의사항이나 전달하고자 하는 내용이 있는 경우 치수 측정하는 열린옷장 옷장지기에게 이야기 해주시면 됩니다. 모든 내용은 대기실 정면에 있는 모니터를 통해 안내됩니다. 모니터에 안내내용을 잘 지켜봐주세요.

**Comment by aanoaa** [comment]
대여자에게 노출이 되는 화면이라면 디자인도 중요하지 않을까 싶습니다.

**Comment by aanoaa** [comment]
도메인이 monitor 인데, visit 에 더 어울리는 기능이 아닐까 합니다.(아닌가?)

인증절차 없이 상태를 변경 할 수 있도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa #150 에 진행에 필요한 내용을 입력해 놓았습니다.

**Comment by 10001if** [comment]
![79b1184fa52a7817fcda5899b8b52a9f](https://cloud.githubusercontent.com/assets/4696328/25211101/598d1442-25be-11e7-964b-6781847e77ec.png)

@MoDoLEE 님의 의견입니다. 

사용자가 직접 터치 스크린을 통해서 예약을 한다면 아예 숫자 키패드를 띄워주면 어떨까 합니다. 사진은 주민번호이지만 우리는 전화번호를 입력받을 수 있게 하면 어떨까요? 참고로 제가 직접 방문해봤던 안과입니다. http://iloveeyecom.tistory.com/771

@aanoaa 바로 입력할 수 있어서 더 직관적이고 쉽게 이해할 수 있을 것 같습니다. 화면에 주민번호를 입력 할 수 있는 번호가 삽입 될 수 있도록 요청드립니다. 

그런데 이 경우에는, 화면처럼 입력 완료 버튼이 있으면 터치스크린 이용자 입장에서 더 편리할 것 같습니다. 다만, 입력 완료 후에는 대기실로 향하는 안내가 새창으로 넘어가는 것이 좋은지 의견을 듣고 싶습니다.

**Comment by aanoaa** [comment]
ipad 류를 사용한다면 새로고침 되었을때 자동으로 키보드가 떠있긴 할겁니다.
터치가 되는 모니터에서 웹프로그램이 어떻게 동작되는지 모릅니다.

터치가능한 모니터가 있어야 테스트가 가능할 것 같습니다.

텐키만 있는 키보드랑 마우스 놓고 써도 될 것 같습니다.

**Comment by aanoaa** [comment]
한화면에서 처리한다면, 항상 텐키가 크게 떠 있으면 안내 화면이 좁을 것 같습니다.

**Comment by aanoaa** [comment]
터치스크린을 사용하기로 결정된건가요?
그렇지 않다면 마우스로 숫자를 누르는게 바보같아 보일 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 터치스크린으로 결정이 되었습니다. 공간 배치와 관련해서 컴퓨터를 그냥 쓸지 고민이 되었는데. 터치스크린 모니터를 구매하여 사용할 계획입니다.

**Comment by aanoaa** [comment]
터치스크린으로 사용할 것이라서 항상 키패드가 보이도록 해야 합니다.

- 키패드의 숫자를 누르면 검색창에 반영되어야 합니다.
- backspace 와 reset 버튼도 필요합니다.

**Comment by aanoaa** [comment]
![2017-05-01 09-26-15](https://cloud.githubusercontent.com/assets/170528/25569390/5cdb3db8-2e51-11e7-99b2-9505c45ebb94.png)

**Comment by pingpongworks** [comment]
확인했습니다~ 근로자의 날 근로해주셔서 감사합니당~
