### ISSUE TITLE
"탈의실 화면" 에서 클릭시 탈의실에 엑티브 표시를 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#15]
잘쓰고 있는데요. 한가지 요청이 들어와서요.
현재는 탈의실에서 의류를 탈의하는 분들에 대한 1:1 담당이 이뤄지지 않고 있습니다.

때문에 어떤분이 어떤 옷을 몇 번 갈아입었는지 확인이 되지 않습니다.
(기존에는 1:1 담당이었기 때문에 담당자가 정보를 알고 있는 상황 / 현재는 1명이 대기실의 사이즈를 보고 옷을 찾아 탈의실에 넣어두면 / 다른 1명이 2차로 옷을 골라주고 있음)

그런데 어떤 경우에는 더이상 옷을 찾아드려도 의미가 없는 경우가 있습니다.
(통상 처음에 찾아드리는 옷이 가장 잘 맞고 그 다음부터 잘 맞을 확률이 떨어짐)
그래서 더 이상 옷을 찾아드리는 것이 의미가 없다고 생각하는 분이 있다면 그 탈의실에 클릭을 하여 탈의실 테두리가 보라색으로 변하게 하고 싶습니다. 보라색으로 변한 탈의실은 옷을 골라드리는게 의미가 없다고 판단하고 벨로 호출을 하면 정직하게 말씀드리려는 의도입니다. ^^

기존에 의류준비화면 에서 해주셨던 것처럼 해주시면 좋을 것 같습니다.

@aanoaa 요청드립니다. ^^

**Comment by aanoaa** [comment]
지금은 바뀌어서 탈의실 + 의류준비 로 바뀌었지만 여전히 active 상태가
필요합니다. 문제는 상태변경과 달리 active 상태는 실시간으로
다른이용자들과의 내용이 공유가 안되고 있기 때문에 이를 수정해야
합니다.

**Comment by aanoaa** [comment]
- `/preparation`
- `/room`
- `/select`

위 3개의 주소중에 어디에서 사용하실 건가요?
제가 알기로는 `/preparation` 만 사용중이신걸로 알고 있는데,
저기에서는 active 상태로 변경하는 기능이 없거든요.

그런데 어제 active 상태변경하는 기능이 동작하고 있다고 하셔서
다른곳에서 되어야 하는 기능인지 어떤지 알아야 합니다.

**Comment by 10001if** [comment]
제가 좀 헷갈렸는데요. 저는 /select에서 상태변경하면 /preparation에서 반영이 된다고 잘못 생각하고 있었네요.
/preparation 에서만 active 상태변경하는 기능이 되면 될 것 같습니다. 각자 스마트폰으로 치수 확인하고, 사람을 누르면 상태가 변경되고(테두리선) 그 결과가 현장 모니터에서도 적용되면 될 것 같습니다. ^^

**Comment by aanoaa** [comment]
오늘 저녁에 적용하도록 하겠습니다.
내일부터는 사용가능합니다.

**Comment by aanoaa** [comment]
배포하였습니다.
사용법은 그냥 클릭 혹은 터치 입니다.

**Comment by aanoaa** [comment]
제대로 동작하지 않습니다.

**Comment by aanoaa** [comment]
PC 화면에서는 잘 동작합니다.
PC 에서 상태를 변경하면 휴대폰에 반영됩니다.

문제는 휴대폰에서 상태를 변경하면 PC 에서는 반영되는데 폰에서는 반영되지 않습니다.

**Comment by aanoaa** [comment]
iOS - chrome 에서 테스트해보았습니다.

**Comment by aanoaa** [comment]
http://stackoverflow.com/questions/7810229/jquery-toggleclass-bug-on-iphone

검색을 조금 해보았습니다.

**Comment by aanoaa** [comment]
> Turns out the js was fine. The real problem was the css hover
> class. On an iPhone the last element you click on persists as a
> hover state. Removing the css hover class (not needed for my mobile
> site version) fixed this.

**Comment by aanoaa** [comment]
문제를 해결하고 `v0.2.4` 로 배포했는데 실제서버에선 오동작 합니다.

**Comment by aanoaa** [comment]
좀 더 탐구생활 해보겠습니다.

**Comment by aanoaa** [comment]
제 리눅스와 맥장비에서는 모두 동작합니다.
배포환경의 문제가 아닐까 합니다.

**Comment by aanoaa** [comment]
배포환경에 환경변수를 잡아주지 않아서 였는데, 지금은 해결되었습니다.

자세한건 https://github.com/opencloset/monitor/issues/46#issuecomment-107385295

**Comment by aanoaa** [comment]
이게 버그가 있습니다.
정확하게 동기화되도록 해야합니다.
여러 상황에 대응하도록 테스트를 더 해봐야 합니다.
