### ISSUE TITLE
의류추천 프로세스의 CPU 점유율이 높음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#151]
서버에 장애가 날 지경입니다.
잘못된 부분을 고쳐야 합니다.

**Comment by aanoaa** [comment]
내부 버그질라에 적어놓긴 했지만 다시 적습니다.

`opencloset/monitor/bin/suggestion_consumer.pl` 에서 의심되는 것은 `/tmp` 디렉토리에 `Directory::Queue` 를 사용하고 있는데,
현재 생성된 directory 갯수가 `20115` 개 입니다.

    $ ls -l | wc -l
    20115

**Comment by aanoaa** [comment]
https://serverfault.com/questions/506465/is-there-a-hard-limit-to-the-number-of-files-a-directory-can-have

> It depends on your filesystem. I'm going to assume it's ext4:
> 
> The maximum number of files is global, not per directory, and it's determined by the number of inodes allocated when the filesystem was created. Try running the following command to see the number of inodes per filesystem.

--------------------------

    $ df -T
    Filesystem                                    Type     1K-blocks     Used Available Use% Mounted on
    rootfs                                        rootfs    10190136  6779472   2869992  71% /
    /dev/vg-vol0/lxc_opencloset1.silex.kr         ext4      10190136  6779472   2869992  71% /
    udev                                          devtmpfs     10240        0     10240   0% /dev
    /dev/vg-vol0/lxc_opencloset1.silex.kr_storage ext4     206293688 15074604 180716940   8% /storage
    /dev/vg-vol0/lxc_opencloset1.silex.kr_var     ext4     103081248  3978176  93843808   5% /var
    tmpfs                                         tmpfs      3300840       68   3300772   1% /run
    tmpfs                                         tmpfs         5120        0      5120   0% /run/lock
    tmpfs                                         tmpfs     10558000       76  10557924   1% /run/shm

rootfs 는 `ext4` 입니다.

    $ df -i
    Filesystem                                      Inodes  IUsed    IFree IUse% Mounted on
    rootfs                                          655360 250466   404894   39% /
    /dev/vg-vol0/lxc_opencloset1.silex.kr           655360 250466   404894   39% /
    udev                                           4123811   1054  4122757    1% /dev
    /dev/vg-vol0/lxc_opencloset1.silex.kr_storage 13107200    659 13106541    1% /storage
    /dev/vg-vol0/lxc_opencloset1.silex.kr_var      6553600 122890  6430710    2% /var
    tmpfs                                          4126050     29  4126021    1% /run
    tmpfs                                          4126050      1  4126049    1% /run/lock
    tmpfs                                          4126050     61  4125989    1% /run/shm

655360 중 250466 개를 사용하고 있습니다. `/tmp/opencloset/` 의 디렉토리 갯수가 문제는 아닌 것 같습니다.

**Comment by aanoaa** [comment]
`/tmp/opencloset/monitor` 에 생성된 디렉토리를 삭제 했습니다.

    $ /tmp/opencloset/monitor$ rm -rf *

**Comment by aanoaa** [comment]
복잡한 처리를 하진 않습니다.
queue 를 순회하면서 작업이 있을때마다 opencpu 의 의류검색 HTTP API 를 호출해서 결과를 redis 에 저장하는 프로세스입니다.

복잡한 연산은 opencpu 에서 처리하므로 단순하게 요청->응답->저장 합니다.

왜 CPU 를 20%~40% 점유하는지 모르겠습니다.
코드의 어떤 부분이 문제인지도 감이 오질 않습니다.

- Queue 순회
- Redis 에 저장

둘중 하나 인 것 같습니다.
Directory::Queue 대신에 Minion(backend SQLite) 를 사용하도록 바꿔보도록 하겠습니다.

**Comment by aanoaa** [comment]
동작하도록 변경하고 배포하였습니다.
익일 모니터링이 필요합니다.
@yongbin

**Comment by yongbin** [comment]
늦었지만 이슈 확인했습니다. 경험상 ext4 파일시스템의 경우 한 디렉토리 내부에 너무 많은 파일(디렉토리)가 존재할 경우 관련 디렉토리에서 작업을 할때 전체적으로 iowait 때문에 응답시간이 늦어지는(그래서 결과적으로 CPU 점유가 올라가는) 경향이 있었습니다. Queue의 backend를 디렉토리에서 sqlite를 백엔드로 사용하는 minion 으로 변경하신건 적절한 결정이었다고 생각합니다.
