### ISSUE TITLE
TTS를 이용해서 탈의실로의 입장안내

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#154]
https://github.com/opencloset/opencloset/issues/1202 를 이어받아서 진행합니다.

**Comment by aanoaa** [comment]
다양하게 시도해봤는데
`홍.길.동.님. 11번 탈의실로 입장해주세요` 처럼 변환하는 것이 가장 듣기 편한 것 같습니다.

**Comment by aanoaa** [comment]
[WebService::Naver::TTS](https://github.com/aanoaa/p5-WebService-Naver-TTS) 모듈을 CPAN 에 업로드 하였습니다.
이 모듈을 사용해서 text 를 음성으로 변환하도록 하고 음성 파일을 가지고 monitor 에서 처리해야 하겠습니다.

**Comment by aanoaa** [comment]
http://search.cpan.org/~aanoaa/WebService-Naver-TTS-v0.0.1/lib/WebService/Naver/TTS.pm

**Comment by aanoaa** [comment]
변환된 파일용량이 `45k(46505)` 입니다.
캐시한다고 하면 100,000개 했을 때에 5GB 가 안됩니다.

         10  450KB
        100  4.5MB
      1,000  45MB
     10,000  450MB
    100,000  4.5GB

11번 탈의실까지 있으니까 이름 한개당 11개씩 파일을 가질 수 있습니다.

**Comment by aanoaa** [comment]
이름만 요청하고 나머지 부분은 붙여서 연속으로 재생시키면 더 효율적일 수 있습니다.

    홍.길.동.님.

    1번 탈의실로 입장해주세요
    2번 탈의실로 입장해주세요
    ...
    11번 탈의실로 입장해주세요

**Comment by pingpongworks** [comment]
TTS 안내 너무 좋습니다. 감사합니다.

**Comment by aanoaa** [comment]
왜 인지 안된다고 합니다.

**Comment by aanoaa** [comment]
naver api 에는 문제가 없습니다.
이상한 점은 job queue 의 로그가 찍히고 있지 않다는 것입니다.

**Comment by keedi** [comment]
잘 되던 것이 안되는 상황이니까 기존 이슈는 잘 끝난 것이고, 별도의 이슈를 열어서 정리하고 해결하는 것이 나을 듯 합니다. :)

**Comment by aanoaa** [comment]
ubic 으로 돌던 queue 를 내리고 직접 foreground 로 띄워놓고 살펴봤습니다.
의류준비 -> 탈의실로 변경되었음에도 job 이 실행되지 않아서 enqueue 가 문제인 것 같아서
monitor web 서비스를 재시작 해주었더니 동작합니다.

여전히 job queue 의 로그메세지가 남지 않고 있는데 이것은 ubic 의 설정이 잘못된 것 같습니다.

**Comment by aanoaa** [comment]
현재 설정파일입니다.
ubic 문서를 다시한번 꼼꼼히 읽어봐야 하겠습니다.

``` perl
#!/usr/bin/env perl
use Ubic::Service::SimpleDaemon;
my $home    = "/home/opencloset";
my $root    = "$home/service/monitor.theopencloset.net";
my $service = Ubic::Service::SimpleDaemon->new(
    {
        bin    => "$root/scripts/monitor minion worker",
        cwd    => $root,
        stdout => "$root/log/minion.stdout",
        stderr => "$root/log/minion.stderr",
        env    => {
            MOJO_CONFIG                 => 'monitor.conf',
            MOJO_MODE                   => 'development',
            OPENCLOSET_MONITOR_EMAIL    => 'xxxxxxxxxxx',
            OPENCLOSET_MONITOR_PASSWORD => 'xxxxxxxxxxx',
            OPENCLOSET_NAVER_TTS_CLIENT_ID     => 'xxxxxxxxxxxxxxxxxxxx',
            OPENCLOSET_NAVER_TTS_CLIENT_SECRET => 'xxxxxxxxxx',
        }
    }
);
```

**Comment by aanoaa** [comment]
web 서비스를 재시작해서 해결은 되었습니다.
job queue 의 로그문제는 따로 이슈를 열도록 하겠습니다.
