### ISSUE TITLE
무인 예약 확인 시 목록 표시 없이 바로 버튼 표시되도록 수정

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/monitor#157]
#148 이슈와 연관되어 있습니다.
무인 예약 확인 시 전화번호 입력 후 검색을 누르면 검색 사이트의 자동완성과 같은 목록이 뜨게 되는데 대여자분들이 그 목록을 클릭해야 된다는 것을 인지하지 못합니다.
그래서 검색 버튼을 누를경우 바로 입장 버튼이 표시될 수 있도록 해주셨으면 합니다.

**Comment by pingpongworks** [comment]
@aanoaa 님이 모를리 없다고 하셨던 걸 모르는 분들이 발생하고 있는 거 같습니다^^

본인의 예약내역이 떴을 때 

> 나의 예약내역을 클릭한 후, 아래 예약확인 버튼을 눌러주세요

와 같은 안내가 뜨면 좋을 거 같습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
