### ISSUE TITLE
무인예약확인 화면에서 자주 오류가 발생함

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#163]
theopencloset.net/reservation 의 화면이 아래와 같은 상태로 자주 오류가 나고 있습니다.
![_20171102_170225](https://user-images.githubusercontent.com/4696328/32318347-5b6ed5bc-bffa-11e7-9544-c345ad5bc1e1.jpg)

빈번하게 예약확인 모니터에 이런 화면이 뜨는데, 그 빈도는 체감으로는 30분에 한 번정도이고 이 때문에 수동으로 예약 페이지를 다시 켜야 한다고 합니다. 원인은 모르겠지만 가끔 홈페이지 검색 로딩이 느려질 때, 대여자분이 오셔서 예약확인을 하시면 저런 현상이 나타나는 것 같다고 합니다. 확인 부탁드립니다. @keedi @aanoaa

**Comment by aanoaa** [comment]
원인 파악을 해보았습니다.
사용자가 보는 화면은 `GET /reservation/:yyyy-mm-dd` 입니다.
이때에 Not found 에러는 발견하지 못했고, 사용자가 `방문확인 버튼을 누르고 입장해주세요` 버튼을 눌렀을때에 발생했습니다.
`GET /reservation/visit` 요청에서 'Not found' 응답이 많았습니다.

- monitor 에서 staff 서비스로 상태변경(방문예약 -> 방문)을 요청합니다.
- 이때의 timeout 이 3초로 설정되어 있습니다.
- 3초 안에 응답을 받지 못합니다.(이유는 더 알아봐야..)
- 내부의 원인에 의해 상태를 변경하지 못하고 사용자에게는 "상태를 변경하지 못했음" 오류(error code 500)를 응답합니다.
- 그런데 500 error code 에 대한 template 을 찾지 못해서 not found 가 발생합니다.

monitor 에서 개선될 수 있는 부분은 적절한 오류 안내입니다.
raptor not found 대신에 "대여 프로그램이 응답하지 않습니다. 다시 시도해주세요(또는 직원에게 문의해주세요)" 등의 친절한 안내 메세지를 보여줄 수 있습니다.

특정 주문서의 id 를 가지고 상태를 변경을 처리하는 것은 간단한 작업이지만 staff 에서는 어떠한 이유에서인지 응답을 하지 못했습니다.
근본적인 해결을 위해서는 이부분을 확인해봐야 합니다.

**Comment by aanoaa** [comment]
#148 에서 진행된 작업입니다.

**Comment by aanoaa** [comment]
![exception](https://user-images.githubusercontent.com/170528/32339618-afe25df8-c03b-11e7-9dbf-443c15056532.png)

에러가 발생했을때에 이런 화면이 나오도록 하였습니다.
고객이 스스로 재시도를 할 수 있는 기회가 있기 때문에 컴플레인이 줄어들 것으로 믿습니다.

**Comment by aanoaa** [comment]
플랫폼 이전을 위해 했던 작업으로 인해 예기치 못한 오류가 발생될까 두렵습니다.
제가 실시간으로 대응할 수 있는 상황에서 적용하도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 오류 체크 수시로 하면서 다시 상황 이야기 드릴게요. 신경써서 오류 페이지 수정해 주셔서 감사드립니다.

**Comment by aanoaa** [comment]
적용하였습니다.
혹시 문제가 발생하면 말씀해주세요.
바로 이전버전으로 복구하도록 하겠습니다.

cc @10001if @pingpongworks

**Comment by aanoaa** [comment]
제가 말하는 문제는 이 예약화면을 포함해서 모든 monitor 서비스를 뜻 합니다.
