### ISSUE TITLE
preparation 화면에서 '입고감 or 기록요망' 확인이 가능하도록

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/monitor#168]
*현재 상황*
**포장하지 않고 입고가려는 대여자의 경우**
현재> 1. 신체치수 단계에서 사용자정보 중 착용여부('안입고감'or '입고감')를 선택 >> 2. 대여를 결정한 후 포장, 결제단계에서 착용여부 확인가능 >> 입고가는 경우 대기실에서 입은 채로 바코드를 찍을 수 없으므로 다시 안쪽으로 안내해야 하는 불편함이 있음. 
![image](https://user-images.githubusercontent.com/17288038/34902601-55c06bd0-f862-11e7-84eb-b6ca18a50adb.png)

**실제 대여일보다 미리 입어보러 온 경우**
현재> 1. 신체치수 단계에서 실제 대여일을 확인 >> 2. 실제대여일이 많이 남아있는 경우 입어보았던 의류를 기록해놓아야 나중에 실제 대여하러 왔을 때 참고가 가능하므로 사용자정보 설명 란에 기록요망이라고 적어놓음 >> 그러나, 의류준비하고 탈의실에서 일하는 옷장지기들이 설명란의 내용을 지속적으로 인지하기 어려움. >> 대여자는 기록에 대해 명확히 모르므로 기록을 요청하지 않고 그냥 귀가하여 나중에 컴플레인이 생기는 경우 발생   

* 위의 미리 입어보러 온 경우는 입어본 후 나중에 온라인으로 대여하려는 경우도 포함됩니다

위와 같이 최근 바로 입고가는 경우, 기록이 필요한 경우가 많아지고 있어 개선되었으면 하는 부분 요청드립니다.

    *모니터 변경 요청사항*
1. **'사용자정보 입력시 입고감 or 기록요망을 선택하면 >> preparation 탈의실 화면에서 바로 확인 가능하도록 함**
현재 탈의실 정보 중 예약시간은 의류준비중에는 필요한 정보가 아니므로, 예약시간 대신에 입고감 or 기록요망이 표기되면 좋겠습니다.
![image](https://user-images.githubusercontent.com/17288038/34902755-e473c10e-f864-11e7-814c-40bc8cc4d7d8.png)

2. **preparation화면에서 직접 변경도 가능하도록 함**
현재는 탈의실 우클릭하면 의류준비/수선/포장 상태를 변경할 수 있는데, 입고감/기록요망 항목을 추가하여 입고감/기록요망을 선택할 경우 현재의 예약시간 자리에 표기될 수 있으면 좋겠습니다. 탈의실에서 갑자기 입고가는 것으로 계획을 변경하는 분들이 있어 필요로 하는 기능입니다.
![image](https://user-images.githubusercontent.com/17288038/34927315-8f6f2bf4-f9f8-11e7-9bad-67ac5801e829.png)

요청해주신대로 모니터에서 수정되었으면 하는 부분만 정리했습니다. staff 변경요청내용은 https://github.com/opencloset/opencloset/issues/1398 에 따로 정리해서 등록했습니다. 

위와 같이 수정되면 옷장지기들이 놓칠까봐 모니터 화면에 메모지를 붙이거나, 서로 계속 말로 인지를 시켜야하는 불편함이 해소되는 것은 물론, 대여자에 대한 서비스 만족도도 높아지리라 예상됩니다. 설명이 부족한 부분 있으면 말씀 부탁드립니다.

**Comment by keedi** [comment]
staff 에서 변경되어야 할 부분과 monitor 에서 변경되어야 할 부분을 구분하셔서 staff 쪽에도 이슈를 등록 부탁드립니다.

**Comment by pingpongworks** [comment]
알겠습니다. 구분해서 정리하겠습니다.

**Comment by pingpongworks** [comment]
탈의실 개수가 15개로 많아짐에 따라 모니터에 메모지로 `입고감` `기록요망`을 표기하는게 너무 복잡해지고 있습니다. 바쁜 시즌이 오기 전에 작업 부탁드리고 싶어, 이슈 우선순위로 옮깁니다.

**Comment by aanoaa** [comment]
`기록요망`이 뭔지 모르겠습니다.

**Comment by aanoaa** [comment]
입어만 보고 나중에 혹은 온라인으로 대여하는 분들이 많아져서, 옷장지기의 불편함을 해결하기 위해 진행되던 이슈입니다.
https://github.com/opencloset/opencloset/issues/1102

**Comment by aanoaa** [comment]
기록요망은 옷장지기들끼리 사용하는 용어이고 시스템에는 반영되어 있지 않습니다.
입고감이면서 기록요망일 수 있습니다 이를 적절히 대처해야 합니다.

제가 생각한 임시방안인데, 탈의실 박스를 클릭하면(이름을 제외하고) 테투리가 보라색으로 변경되는 것 알고 계신가요?
전에는 active 함을 표시하기 위해(누군가가 지금 의류를 고르는 중이다) 사용되었던건데 요즘에도 사용하는지 모르겠습니다.

만약 사용하지 않고 있다면, 임시방편으로 이 기능을 기록요망으로 대신할 수 있지 않을까 싶습니다.

어느 시점에 의류를 기록하는지도 궁금합니다.

**Comment by aanoaa** [comment]
방문예약 시간을 누르면 `입고감` 으로 변경됩니다.
토글버튼입니다. `입고감` 을 누르면 다시 방문예약 시간으로 변경됩니다.

**Comment by aanoaa** [comment]
아직 기록요망에 대한 요청이 해결되지 않았기 때문에 이슈는 닫지 않겠습니다.

**Comment by pingpongworks** [comment]
>제가 생각한 임시방안인데, 탈의실 박스를 클릭하면(이름을 제외하고) 테투리가 보라색으로 변경되는 것 알고 계신가요?
전에는 active 함을 표시하기 위해(누군가가 지금 의류를 고르는 중이다) 사용되었던건데 요즘에도 사용하는지 모르겠습니다.

보라색 테두리는 탈의실 번호가 지정되어 있지 않은 대여자(교환, 반납, 예기치않은 입고감 등)가 옷을 갈아입어야할 때 사용하고 있습니다. 

>어느 시점에 의류를 기록하는지도 궁금합니다.
1. 대여자가 마음에 드는 옷을 선택한 후 나중에 이 옷으로 대여하고 싶다고 의사를 밝힘
2. 의류를 탈의해서 수트라이브러리 안의 옷장지기에게 전달해줄 것을 요청함
3. 의류를 전달받고 귀가하시라고 한 후 사용자정보 비고란에 의류코드를 입력함

>입고감이면서 기록요망일 수 있습니다
`입고감`과 `기록요망`의 용어는 현장에서 대여업무를 할 때는 구별되어서 인지가 되어야 합니다.
-`입고감`은 입은 채로 바코드를 찍어야하므로 의류선택이 끝나면 수트라이브러리 안으로 대여자를 불러 바코드를 찍습니다
-`기록요망`은 위에서 이야기한 것처럼 탈의한 의류를 받아 기록하기 때문에 대여자에 대한 안내가 달라집니다.

**Comment by pingpongworks** [comment]
![image](https://user-images.githubusercontent.com/17288038/37392488-a83aa398-27b1-11e8-84f1-ae551d7c577d.png)

`입고감` 버튼 사용해보니까 매우 편리합니다!

예약시간을 한번 누르면 `입고감`
또 한번 누르면 `기록요망`으로 바뀌도록 할 수는 없을까
조심스럽게 제안해봅니다~

**Comment by pingpongworks** [comment]
**https://github.com/opencloset/opencloset/issues/1398 에서 요청드렸던 내용으로 
요청내용 수정합니다.**  @aanoaa 

사용자정보 "착용여부"에서
`기록 요망`을 선택했을 경우에도 preparation 예약시간 자리에
`기록 요망`이 표시되도록 요청드립니다.

기록이 필요한 경우는 대부분 착용일이 많이 남았을 경우
사이즈측정 단계에서 발견되므로
preparation 화면에서 직접 수정 기능은 없어도 될 듯 합니다.

    정리하자면, 
    상황 선택에 따라 현재의 예약시간 자리에 
    `입고감` `기록 요망` 둘 중 하나가 표시되도록 요청드립니다.

**Comment by aanoaa** [comment]
표시되도록 바꾸었습니다.
하면서 토글 기능도 추가하였습니다.

예약시간 -> 입고감 -> 기록요망 -> 입고감+기(록요망) -> 예약시간 -> ...
