### ISSUE TITLE
임의로 주문서상태가 '의류준비'로 변경됨

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/monitor#173]
orders/94128
3월 3일 (토) 2시경 / `방문`에서 `의류준비`로 자동으로 상태 바뀌는 오류 발생

**Comment by pingpongworks** [comment]
orders/93899
2월 27일 오후2시경 / `탈의중`에서 `의류준비`로 상태바뀌는 오류 발생

**Comment by pingpongworks** [comment]
**orders/94856**
03월 11일 10시 19분 / `치수측정` 중에 `의류준비`로 상태 바뀌는 오류 발생

**Comment by aanoaa** [comment]
```
[Sun Mar 11 10:19:14 2018] [debug] PUT "/api/order/94856.json"    방문 -> 치수측정
[Sun Mar 11 10:19:26 2018] [debug] GET "/user/92554"              치수측정을 위해 대여자 프로필화면을 열고
[Sun Mar 11 10:19:27 2018] [debug] GET "/api/order/94856.json"    ???
[Sun Mar 11 10:19:27 2018] [debug] PUT "/api/order/94856.json"    치수측정 -> 의류준비
```

스스로 상태가 변경된건 아니고, 상태를 의류준비로 바꿔달라는 요청이 있었습니다.
사용자 프로필을 열람한 직후에(1초뒤) 발생됐습니다.

요청경로까지는 기록해두지 않아서 어디에서 이런 요청이 발생한 것인지는 모르겠습니다.

**Comment by aanoaa** [comment]
버그 아닌 것 같습니다.

**Comment by pingpongworks** [comment]
@aanoaa 옷장지기들이 메신저에 올려주는 건을 모두 git에도 공유하고 있는데
음...버그와 실수를 구분해내기가 점점 어려워지네요.
가능한대로 파악해보고 이슈 올릴 수 있도록 해보겠습니다.

**Comment by pingpongworks** [comment]
2018년 하반기 이후로 유사한 현상이 나타나고 있지 않기 때문에 이슈 닫겠습니다. 왜 상황이 호전되었는지는 정확히 모르겠지만 원인파악이 당장 꼭 필요하다고 생각되지 않습니다.
