### ISSUE TITLE
repair (수선 담당자 화면) 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/monitor#176]
수선 담당자가 보는 화면에 문제가 생겼습니다.
증상은 다음과 같습니다.

- 남자, 여자 인형들과 수선 요망 내용이 새로고침 하면 나타났다가 몇 분 후에는 자꾸 사라집니다.
- 수선을 마친 후 체크박스를 클릭해도 반응이 없습니다.

문제가 뭔지 밝혀주시길 부탁드립니다~

**Comment by pingpongworks** [comment]
4층 아이패드 리페어 페이지가 계속 리셋되어서 화면에 목록만 뜨고 나머지는 아무것도 뜨지 않습니다~ 사파리 새로고침하고 아이패드 껐다가 다시 켜봐도 동일한 상태네요 ㅠㅠ 왜 그러는 것일까요... 확인 부탁드려요!  

옷장지기들이 불편을 호소하고 있네요.  우선적으로 확인부탁드립니다.

**Comment by aanoaa** [comment]
금요일 제 피시에서 모니터링 해봤는데 문제 없었습니다

아이패드에서만 그런건가요?

**Comment by pingpongworks** [comment]
아니요, 5층 다른 피씨에서도 작동이 되지 않는다고 합니다.

**Comment by pingpongworks** [comment]
현 시점에서 다시 한번 체크해보라 하겠습니다

**Comment by aanoaa** [comment]
수선 체크박스가 눌러지지 않는 문제를 확인했습니다.

모니터링할때에 아이콘 대기목록이 잘 바뀌고 있어서 문제가 없는 줄 알았습니다.

**Comment by aanoaa** [comment]
Font Awesome 버전을 올리면서 발생한 문제입니다.

v4 에서는 마크업이 그대로 반영이 되었는데, v5 에서는 `<i>` 태그가 `<svg>` 로 변경됩니다.

template
``` html
<i class="fa fa-check-square"></i>
```

v4
``` html
<i class="fa fa-check-square"></i>
```

v5
``` html
<svg class="fa fa-check-square">...</svg>
```

수선화면의 js 에서 `.fa` 셀렉터를 사용했기 때문에 문제가 발생했습니다.

**Comment by aanoaa** [comment]
> 남자, 여자 인형들과 수선 요망 내용이 새로고침 하면 나타났다가 몇 분 후에는 자꾸 사라집니다.

이거는 뭔지 모르겠습니다.

**Comment by pingpongworks** [comment]
지금 확인해보니 정확한 상황은 이렇습니다.

- 체크박스가 눌러지지 않는 문제는 모든 피씨에서 발생 
- 내용이 떴다가 사라지는 문제는 아이패드에서만 발생

아이패드 문제는 아이패드 노후화 문제일수도 있습니다만 두 가지 문제가 동시에 발생한 것으로 보아 관련성이 있을지는 좀더 알아봐야 할 것 같습니다. 

**일단 체크박스 문제 해결 먼저 부탁드립니다~**

**Comment by aanoaa** [comment]
아이패드의 OS 버전을 업그레이드 해보세요.
(OS 를 업그레이드 해야 브라우저도 업그레이드 되지 않나요?)
제가 가지고 있지 않아서 테스트해볼수가 없네요.

**Comment by aanoaa** [comment]
대령님 입장에서는 거의 모든 이슈가 `help wanted` 일 겁니다.
굳이 저 라벨을 쓰지 않으셔도 됩니다.
이슈의 우선순위는 https://github.com/orgs/opencloset/projects/1 에서 정해주세요.
`help wanted` 는 보통 제가 팀원의 누군가에게 도움이 필요할때 사용합니다.

**Comment by aanoaa** [comment]
버튼이 눌리지 않는 문제는 해결했습니다.
아이패드에서 오동작이 해결되지 않는다면 다시 이슈를 열어주세요.

**Comment by pingpongworks** [comment]
@aanoaa ㅋ 모든 문제가 헬프원티드 맞습니다. 앞으로는 마음속으로만 라벨 달겠습니다~

리페어화면 버튼 잘 눌립니다. 확인했습니다. 감사요~

**Comment by aanoaa** [comment]
대기자 목록이 아이패드에서 제대로 동작하지 않는다고 합니다.
font awesome 버전을 낮춰서 제대로 동작할 수 있도록 하겠습니다.

**Comment by aanoaa** [comment]
사용하는 icon 라이브러리 버전을 올리면서 아이콘 표시방법을 바꾸었었는데,
이를 예전처럼 사용하도록 수정하였습니다.

SVG with js -> Web fonts with css

혹시 그래도 안된다면 알려주세요.

**Comment by pingpongworks** [comment]
@aanoaa 아이패드, 아이콘 버전 수정 후 전혀 문제 없습니다. 감사합니다~^^
