### ISSUE TITLE
탈의공간 전용 대쉬보드 제작

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/monitor#181]
탈의실 개수가 많아지고, 의류선택 방법이 달라짐에 따라 탈의실 내부에서 필요한 정보를 적절한 시기에 안내하는 **탈의실 전용 대쉬보드**의 필요성이 대두되고 있습니다.
좀더 구체적으로 필요한 이유를 설명하자면 이렇습니다. 

`현재 대여방식`
1. 예약확인
2. 신체치수 측정하면서 탈의실번호 안내
3. 대여자가 의류준비를 기다리지 않고 바로 탈의실로 입장하여 셔츠, 블라우스 등 수트 외 품목들을 선택
4. 옷장지기가 탈의실에 수트를 준비

`문제점`
1. 대여자가 수트외 품목을 고르는데 집중하다보면 신체치수 측정하면서 안내받은 탈의실 번호를 잊음
2. 수트가 준비되었는데도 대여자는 인지하지 못하거나, 인지했더라도 계속 블라우스, 셔츠를 고르고 있어 대여시간이 길어짐

`탈의실 대쉬보드에 기대하는 역할`
1. 대여자가 탈의공간에 들어왔을 때 모니터를 보고 본인의 탈의실 위치를 확인할 수 있음
2. 옷장지기에 의해 수트가 준비되었을 때 다시 한번 탈의실 번호와 함께 "수트가 준비되었음"을 알림으로써 대여자가 수트를 입어보는 행동을 바로 할 수 있도록 함
3. 결과적으로 탈의공간 내에서 대여자의 혼란을 줄이고, 전체 대여시간이 축소되도록 하고자 함.

![- -](https://user-images.githubusercontent.com/17288038/42216280-41f0971c-7efc-11e8-9b76-82036158cc5d.jpg)

대략적으로 이런 식이 아닐까 그림을 그려보았는데요, 실현가능할지 어떤 문제점이 있을지 세세한 고민은 더 필요할 듯 합니다. 같이 고민해주셨으면 하는 마음으로 일단 공유합니다^^

**Comment by aanoaa** [comment]
오늘 미팅 후에 좀 더 개선이 필요한 부분에 대해 이야기를 들었습니다.

치수측정 -> 의류준비 단계에서 대여자에거 탈의실 10번을 사용해 달라고 얘기를 하고,
대여자는 직접 셔츠/블라우스를 고르는 과정으로 변경되었습니다.
이때에 `비고`에 `탈10` 으로 기록하면 의류준비 하시는 분은 의류를 준비하고 `비고`의 `탈10` 을 보고 탈의실 10번에 할당합니다.
이 과정이 번거롭습니다.

치수측정 -> 의류준비 단계에서 바로 탈의실을 할당하고 의류준비 과정에서는 지정된 탈의실로 보낼 수 있도록 해야 합니다.
위에 말씀해주신 탈의실에 대여자를 위한 대시보드가 추가되는 것은 어려운 일은 아닌 것 같습니다.

**Comment by pingpongworks** [comment]
희소식입니다!

**Comment by aanoaa** [comment]
탈의실용 대시보드가 제작된다면 탈의실을 치수측정후에 배정하는 것이 아니라
의류준비가 완료되면 탈의실을 배정해도 되지 않을까요?
탈의실 대시보드의 알람으로 탈의실 입장 안내를 하고요.

**Comment by pingpongworks** [comment]
탈의실을 미리 배정하면 가방 등의 개인 소지품을 탈의실에 놓고 블라우스 구두 등을 고를 수 있어서 대여자의 손이 편해집니다. 

동시에 대기실에 개인소지품을 두지않게되어서 분실 등의 우려가 줄어드니까 신체측정시 탈의실을 배정하는게 낫다고 판단되고 있어요.

**Comment by aanoaa** [comment]
동그라미안에 넣어보려고 했는데 재주가 없어서 어렵습니다.
진행 중인 디자인입니다.

![screenshot-localhost 5000-2018-07-05-14-14-15](https://user-images.githubusercontent.com/170528/42303775-bfd15740-805d-11e8-8f1f-1cd09bae804a.png)

**Comment by pingpongworks** [comment]
동그라미 아니어도 좋습니다^^

**Comment by aanoaa** [comment]
이런건 어떤가요?
탈의실 위치도 이해하기 쉽게 바꿔보았습니다.

![screenshot-localhost 5000-2018-07-05-19-00-07](https://user-images.githubusercontent.com/170528/42316804-abc41620-8085-11e8-8721-18899b396f18.png)

**Comment by pingpongworks** [comment]
오~ 컬러풀! 안내 형태가 대기실 대쉬보드와 같은 연장선상에 있는 느낌이 있네요. 여러 명을 동시에 안내할 수 있는 장점이 있을거 같고요. 2가지안 장단점이 있을거 같은데, 옷장지기들 현장의 의견을 한번 들어봐도 좋을거 같아요. 내일 들어보고 의견 드릴게요~

**Comment by pingpongworks** [comment]
현장 의견을 들어보진 못했는데, 생각해보니까 @aanoaa 님이 제안해주신 보드형태가 더 나을 듯 합니다. 2명이 거의 동시에 의류준비를 끝내는 경우도 있을 수 있고, **"1번 탈의실에 정장이 준비되었습니다"**메시지가 잠깐 떳다가 사라지는 것보다는 2번 탈의실 안내가 나오더라도 모니터에 일정시간 떠 있는 것이 대여자가 고지하기도 나을 듯 합니다. 

탈의실 위치는 모니터가 어느 벽에 설치 되느냐에 따라 다를 듯 한데, 아마도 일단은 타이장과 구두장이 있는 벽에 일단 1개 모니터가 설치될 듯 합니다. 그 위치에 있는 모니터를 보면 제가 그려놓은 아래쪽으로 ㄷ자 위치가 더 인지하기가 쉬울 거 같아요.

**Comment by aanoaa** [comment]
![screenshot-localhost 5000-2018-07-10-15-15-42](https://user-images.githubusercontent.com/170528/42492522-4c89ca88-8454-11e8-8469-efc4db8376da.png)

피드백을 받아서 스타일을 적용하였습니다.
모니터를 설치하는 기간동안 `비고` 를 사용하지 않을 수 있도록 하는 작업을 해야합니다.

**Comment by aanoaa** [comment]
11, 5번이 아래로 길게 보이는건 캡쳐 프로그램 버그입니다.

**Comment by aanoaa** [comment]
치수측정에서 의류준비로 변경할때에 상태 변경 도구로써 시간표탭을 사용하고 있습니다.
시간표에서 치수측정 -> 탈의n 으로 변경하도록 하면 내부적으로

치수측정 -> 의류준비 -> 탈의n -> 의류준비로 변경시키고 이 과정에서 이벤트는 한번만 전달되도록 하면 될 것 같긴합니다.

다만 자동으로 상태가 변경되고 의도와는 동작이 달라서 헛갈리 수 있습니다.

치수측정 -> 탈의n 으로 변경했는데 결과적으로 치수측정 -> 의류준비로 변경되기 때문입니다.
뿐만 아니라 시간표에서 탈의실로 변경할때에 실수가 발생할 수 있습니다.
이미 할당된 탈의실에 넣는다거나..

**Comment by aanoaa** [comment]
before

치수측정 -> 의류준비

말그대로 치수측정 -> 의류준비

-------------------------

after

치수측정 -> 탈의n

조건에 따라 동작방식이 달라집니다.
**처음으로 상태가 탈의로 변경되는 주문서**라면 탈의실에 해당 주문서를 기록해두고,
주문서의 상태는 의류준비가 됩니다.
주문서는 지정된 탈의실로만 이동이 가능합니다.

아직 적용은 안했습니다.
직접 시연하고 피드백 받아서 적용하도록 하겠습니다.

**Comment by pingpongworks** [comment]
넵~

**Comment by aanoaa** [comment]
- 탈의n -> 의류준비
  로 변경되었을때에 탈의실 화면에 표시가 되는게 좋을 것 같다.
- 시간표에서 비어있는 탈의실만 보이는 게 좋을 것 같다.

**Comment by aanoaa** [comment]
탈의실 배경색을 남녀 구분없이 파란색으로 해야합니다.

**Comment by aanoaa** [comment]
하나의 탈의실에 두개 이상의 주문서가 들어갈 일은 테스트할때 말곤 없습니다.
상태를 변경하고자 할때 이미 배정된 탈의실이라면 오류가 발생하도록 해주는게 좋을 것 같습니다.

**Comment by aanoaa** [comment]
`GET /room` 이 제대로 표시되질 않습니다.

https://reactjs.org/docs/optimizing-performance.html#use-the-production-build
production mode 로 build 해서 적용해봐야 할 것 같습니다.

**Comment by aanoaa** [comment]
`webpack.config.js` 의 `mode` 를 `production` 으로 바꾸면
그것이 production build 입니다.

여전히 화면은 제대로 표시되고 있지 않습니다.

**Comment by aanoaa** [comment]
DOMException: "The operation is insecure."
    SecurityError: The operation is insecure.

라고 나오고 있습니다.

**Comment by aanoaa** [comment]
서버에서 build 된 `.js` 파일을 가지고 로컬에서 테스트해보면 위와 같은 에러가 발생하지 않고 동작합니다.
빌드환경에는 문제가 없는 것 같습니다.

insecure 가 발생할만한 동작이,

- 웹소켓 연결
- `axios` 모듈을 이용한 ajax 통신

정도 입니다.

코드에서의 개발환경과 서버의 다른점은 개발환경에서는 웹소켓을 연결할때에 URI scheme 을 `ws` 를 사용하지만,
서버에서는 `wss` 를 사용합니다.

- `ws://localhost:5000/socket`
- `wss://monitor.theopencloset.net/socket`

**Comment by aanoaa** [comment]
https://en.wikipedia.org/wiki/Same-origin_policy 에 대해 테스트 하기 위해서
로컬에서 띄우고 서버로 websocket 연결을 시도했습니다.

    http://localhost:5000 -> wss://monitor.theopencloset.net:80

insecure 에러가 발생하는 대신에 웹소켓연결을 하지 못해서 무한 재연결 시도를 합니다.
이해할 수 있는 정상적인 동작입니다. Same origin policy 를 위반한 것 같지는 않습니다.

**Comment by aanoaa** [comment]
크롬에서 실행해봤습니다.
더 명확한 에러로그를 얻을 수 있었습니다.

> dashboard-room.js:1 Mixed Content: The page at 'https://monitor.theopencloset.net/room' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://monitor.theopencloset.net/socket'. This request has been blocked; this endpoint must be available over WSS.

wss 로 접속해야 하는데 ws 로 접속을 시도하고 있다고 합니다.

``` typescript
    const hostname = location.hostname;
    const port = location.port;
    const protocol = location.protocol;
    const schema = protocol === 'https' ? 'wss' : 'ws';
    const url = `${schema}://${hostname}:${port}/socket`;
    const ws = new ReconnectingWebSocket(url);
```

이 부분에서 잘못된 점이 있습니다.

**Comment by aanoaa** [comment]
27ce803da1d1fb98b8d4f7b0590f5afc60a94f6e 에서 해결되었습니다.

**Comment by pingpongworks** [comment]
@aanoaa 8월말에 50인치 모니터를 장만할 방법이 생겼습니다. 모니터 장만 후에 실제 적용 관련해서 다시 말씀드릴게요~

**Comment by aanoaa** [comment]
TTS 기능이 되면 좋겠다고 합니다.

"12번 탈의실에 의류가 준비되었습니다."

**Comment by aanoaa** [comment]
TTS 를 사용해서 1번 ~ 15번 탈의실에 대한 파일을 만들어놓습니다.

    n번 탈의실에 의류가 준비되었습니다.

이후에는 해당하는 파일만 재생하면 될 것 같습니다.
해당 파일들은 monitor 저장소에 포함되는게 좋을지는 생각해봐야 하는 문제입니다.
일단 서버에만 올려 두도록 하겠습니다.

**Comment by aanoaa** [comment]
아래 스크립트로 mp3 파일을 생성하였습니다.

    use utf8;
    use strict;
    use warnings;
    
    use Path::Tiny;
    use WebService::Naver::TTS;
    
    my $id     = $ENV{'ID'};
    my $secret = $ENV{'SECRET'};
    
    die unless $id;
    die unless $secret;
    
    my $client = WebService::Naver::TTS->new(id => $id, secret => $secret);
    
    for my $n (1..15) {
        my $text = $n . '번 탈의실에 의류가 준비되었습니다.';
        my $mp3  = $client->tts($text);
        my $cache = path(sprintf("./cache/%d.mp3", $n));
        $cache->spew_raw( $mp3->slurp_raw );
    }

**Comment by aanoaa** [comment]
이게 왜 merge commit 이 안보이는지 모르겠네요.

bb7d1766dcb1953da95df6cfa3ceaec3e7cbb901 에서 해결되었습니다.

**Comment by pingpongworks** [comment]
>n번 탈의실에 의류가 준비되었습니다.

**Comment by aanoaa** [comment]
0.0.0.님. n번 탈의실로 입장해주세요.

에서 `n번 탈의실로 입장해주세요.` 가 반복되고 있기 때문에,
작업하는김에 해당파일을 캐시해두고 재사용하게 하였습니다.

`public/tts/index/1.mp3` ~ `public/tts/index/15.mp3` 가 그것 입니다.

용량이 작아서 저장소에 포함해도 되지만 적절하지 않은 것 같아서
서버에 설치만 해두었습니다.
서버를 이전하게 될때에 추가 작업이 필요한 부분입니다.

**Comment by aanoaa** [comment]
[OpenCloset-Common-v0.1.9.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Common-v0.1.9.tar.gz) 배포하였습니다.
TTS 타입상수

-   `$MONITOR_TTS_TO_INDEX`
-   `$MONITOR_TTS_TO_ROOM`

를 추가한 버전입니다.

**Comment by aanoaa** [comment]
배포후에 TTS 로 변환이 되긴하는데 브라우저에서 오디오가 실행되지 않습니다.
audio file 의 URL 이 의심되어서 디버깅하고 있습니다.

**Comment by aanoaa** [comment]
[Sun Sep 30 09:52:10 2018] [info] Worker 4268 started

TTS 는 jobqueue 가 처리하고 있고 worker 는 running 중인데, 
웹서버에서 jobqueue 로 enqueue 가 되지 않는 것 같습니다.

TTS 만 그런 것이 아니고 suggestion 도 함께 동작하지 않습니다.

**Comment by aanoaa** [comment]
웹서버에서 enqueue 가 되지 않는 것 같아서 양해를 구하고 영업시간이지만 서버를 재시작 하였습니다.

**Comment by aanoaa** [comment]
다행히도 재시작후에 정상적으로 동작합니다.

**Comment by aanoaa** [comment]
287d08e30e5c4aa1a812b804c733c402918799ed
