### ISSUE TITLE
재방문시 재방문자의 의류기록을 select 화면에서 알 수 있게함

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#19]
프로그램을 쓰다보니 재방문하신 분들에 대한 기록을 더 명확히 알 수 있게 되었답니다.
그러다보니 전에 빌렸던 의류에 대한 정보를 알고 있으면 굳이 입어보지 않고도 빌려갈 수 있는 상황도 나오고 있어요. 

그런데 우선 이 분이 재방문 하셨을때 전에 입었던 옷이 무슨 옷인지 알려면 치수를 측정하는 사람이 사용자화면에서 주문서를 보고 재방문인지 확인하고, 
![2014-12-27 12 06 18](https://cloud.githubusercontent.com/assets/4696328/5560286/ce3ac07a-8dc0-11e4-84b2-548d62899b8f.png)
재방문 기록을 살펴본 후
![2014-12-27 12 07 04](https://cloud.githubusercontent.com/assets/4696328/5560288/e38bf5a2-8dc0-11e4-86ff-94d92eeb9ef4.png)
품번을 드래그하여 복사한 뒤 
![2014-12-27 12 07 47](https://cloud.githubusercontent.com/assets/4696328/5560290/fd26ffde-8dc0-11e4-9901-e0354293b688.png)
설명 창에 붙여넣어 
최종적으로 /select 화면에서 옷을 고르는 사람들이 알 수 있도록 합니다.
그런데 설명창에 붙여넣을 때 그대로 붙여넣으면 
![2014-12-27 12 09 18](https://cloud.githubusercontent.com/assets/4696328/5560292/39196310-8dc1-11e4-9d7d-ba3989bc63ef.png)
이런 식으로로 진행이 되어 다시 수정하여 입력하는 과정이 필요합니다.

제가 원하는 것은 전에 대여한 기록이 있는 경우 대여자가 전에 입었던 옷 중에 원하는 옷이 있다면 대여기록 중에 하나를 체크하여 모니터에 그 의류 품번과 기증자명을 함께 노출시켜 줄 수 있다면 좋겠습니다. 잘 이해가 안되시면.. 다음에 육성으로 설명해 드리겠습니다. :)

**Comment by 10001if** [comment]
셀렉트 화면에서 대여자의 대여기록을 보여주는데 여기에 기증자명과 옷을 찾을 수 있는 사이즈를 함께 표시하고 싶습니다. 

예1) 한만일 95 J09M 한만일 84 P06E - 남자자켓 (중동), 남자바지 (허리) 
예2) 김소령 84 J0RE 정선경 74 K023 - 여성자켓 (중동), 여성스커트 (엉덩이둘레)

로 표시되었으면 좋겠습니다.

코드만 보고는 의류를 찾을 수 없는 상황이라, 기증자/사이즈를 함께 안다면 의류의 위치를 쉽게 확인 할 수 있기 때문입니다. ^^

**Comment by aanoaa** [comment]
![2015-01-07 14-33-55](https://cloud.githubusercontent.com/assets/170528/5641317/536182ea-967a-11e4-9f79-22b767293bbb.png)

**Comment by 10001if** [comment]
셀렉트 화면에서 대여자의 대여기록을 보여주는데 여기에 기증자명과 옷을 찾을 수 있는 사이즈를 함께 표시하는데 필요한 항목은 다음과 같습니다. 

기존에는 자켓, 바지, 스커트, 셔츠, 구두, 벨트, 타이, 블라우스 모든 대여품목이 보였다면

앞으로는

남성 : 자켓, 바지, 셔츠
여성 : 자켓, 스커트

만 보여주시면 됩니다.

[셔츠는 한만일 96(가슴둘레) 화이트(색상) S07H 기준으로 보여주시면 될 것 같습니다.]

품목을 줄이는 이유는 1. 지나치게 많은 품목으로 인해 /select 화면에서 한명이 차지하는 범위가 너무 커집니다. 2. 실제 구두, 벨트, 타이, 블라우스의 경우 사이즈와 정보를 알아도 의류를 찾는 것이 불가능 한 상황이기 때문입니다. 그래서 필요한 품목만 모니터에서 확인하려고 합니다. :)

형석님이 만들어 주신 내용은 정말 좋습니다! 재대여의 경우에는 대여부담이 엄청 줄어들었네요! ^^

**Comment by aanoaa** [comment]
지금은 찾기 어려우니 빼더라도 나중에 찾기 쉬운 상황이 되면 다시 필요해 질 것 같긴 하지만
나중에 고민하겠습니다.

**Comment by aanoaa** [comment]
전화 통화 했는데,
그냥 남기는게 좋을 것 같다고 합니다.

추가로 셔츠에 대한 사이즈가 필요하고,
모든 품목에 대한 색상도 보여졌으면 좋겠다고 합니다.

**Comment by aanoaa** [comment]
![2015-01-07 17-44-26](https://cloud.githubusercontent.com/assets/170528/5642944/3242a8da-9695-11e4-803d-4ccf167bf5ca.png)

얍
