### ISSUE TITLE
의류준비 기능 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/monitor#192]
4월 21일 (일) preparation 화면에 발생했던 오류 내용입니다. 

- 시각 : 오전 10시 50분 경부터 ~ 11시 36분까지 
- 증상 : 신체치수 측정을 한 후 탈의실을 지정했을 때 새로온 대여자일 경우 의류준비 화면에 주문정보가 떠야 하는데, 그냥 탈의실로 들어가 버려서 새로온 대여자인지 인지할 수 없었음. 인지를 하고 탈의실에서 의류준비로 빼려고 마우스 오른쪽 클릭을 했으나 의류준비/수선 등 상태변경 목록이 뜨지 않았음
- 오류 시각 대여한 자 중에 몇분중에 이전 대여이력중에 데이터에 문제있는 의류를 대여한 것 같다는 개발자 의견에 대여자들 데이터를 찾았음
- `user/112962` 의 11월 17일 대여기록 중 J7RE 자켓 조회 시 502bad gate가 뜨고 자켓, 팬츠는 현재 연체중인 의류인 것으로 보아 발생했던 오류의 원인이라고 추측됨.

오류의 원인이 맞는지 확인부탁드립니다.

**Comment by aanoaa** [comment]
#191 에서 같은 현상이 재발하지 않도록 패치하였습니다.

**Comment by pingpongworks** [comment]
네, 의류 찾아서 기증정보 다시 등록하겠습니다. 감사합니다.
