### ISSUE TITLE
통계시각화

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#22]
사용률, 사용자의 상태별 경과시간 같은 통계를 시각화해서 볼 수 있어야
합니다.

어떤게 필요한지는 @10001if 님이 알고 있습니다.

일단은

- 사용자 상태별 경과시간

이 필요합니다.

사용자별은 의미 없을 것 같고 전체사용자의 평균으로가 의미가 있을 수
있습니다.

y 축은 시간, x 축은 상태(대기중, 치수측정, ..., 입금대기) 로 각
성별로써 평균 이랄까요.

이걸 그래프화 시키는게 목표입니다.

**Comment by yongbin** [comment]
예약쪽에 쌓이는 자료는 다음과 같은 형식이 될 예정입니다. 혹시 더 필요한게 있으면 알려주세요 

https://github.com/opencloset/opencloset/issues/307#issuecomment-68238919

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/318

의 trigger 를 통해 생성된 데이터는 아래와 같습니다.

    +----------+-----------+---------------------+
    | order_id | status_id | timestamp           |
    +----------+-----------+---------------------+
    |      622 |        18 | 2015-01-05 14:11:46 |
    |      622 |        20 | 2015-01-05 14:11:35 |
    +----------+-----------+---------------------+

위의 데이터를 아래와 같이 재가공할필요가 있습니다.

    gender | status | elapsed time
    ------------------------------
      male |     13 |            5    # 대기중
      male |     16 |           20    # 치수측정
      male |     17 |           20    # 의류준비
      male |     20 |           20    # 탈의01
      male |      6 |           20    # 수선
      male |     18 |           20    # 포장
      male |     19 |           20    # 결제대기

    female |     13 |            5    # 대기중
    female |     16 |           20    # 치수측정
    female |     17 |           20    # 의류준비
    female |     20 |           20    # 탈의01
    female |      6 |           20    # 수선
    female |     18 |           20    # 포장
    female |     19 |           20    # 결제대기

**Comment by aanoaa** [comment]
![dashboard 2015-01-05 19-32-49](https://cloud.githubusercontent.com/assets/170528/5612025/ca551c96-9511-11e4-9483-415d784eb459.png)

샘플로 테스트해 보았습니다.
ㅋㅋㅋ

**Comment by aanoaa** [comment]
`#22-statistic-charts` 브랜치에서 작업중입니다.

`scripts/cron-statistics-elapsed.pl` 을 실행하면 재가공된 데이터를 `.opencloset.json` 파일에 갱신합니다.

**Comment by aanoaa** [comment]
![dashboard 2015-01-06 15-34-07](https://cloud.githubusercontent.com/assets/170528/5625198/92e840d2-95b9-11e4-9657-b59d792cc1c6.png)

**Comment by aanoaa** [comment]
어제 offline 에서 얘기해보니 이슈가 커질 것 같습니다.
제가 이해했던 기준과 다르고, 여러모로 시각화 하고 싶어하는 부분이
많았습니다.

- 최근한달이내 남녀별 평균 경과시간을 알고싶다.
- 매일 남녀별로 평균 경과시간을 알고 싶다.

와 같은 구체적인 요구사항이 필요합니다.

어떤식으로 보여지면 좋을지에 대한 그래프가 첨부된다면 더 좋습니다.
x축, y축 에 대한 예시도 좋고요.

**Comment by aanoaa** [comment]
지금 매번 갱신되도록 하고있는 데이터를 일별/주별/월별 등 필요에 따라
남겨두고 접근가능하도록 해야 합니다.

지금 남녀별 경과시간 평균은 파일이 매번 갱신되는데,

    {"orders":{"select":{}},"statistics":{"elapsed_time":{"female":{"18":150,"20":736,"16":130,"17":590,"13":75},"male":{"18":107,"20":1301,"16":161,"17":259,"13":249}}}}

갱신이 아니라 누적되도록 수정해야합니다.

`Jan-7-14:54:27-2015.elapsed.male.tsv`

    18    107
    20    1301
    16    161
    17    259
    13    249

**Comment by aanoaa** [comment]
각 파일별로 링크를 제공하고 해당 링크로 이동하면 그래프를 보여줄 수 있도록 하면
이게 어떤 자료를 나타내는지 알 수 있고 비교하기도 수월하겠습니다.

시스템 모니터링하는 rrd 처럼 말이죠.

**Comment by 10001if** [comment]
형석님.. 여기 들어가서 보려면 어느 주소로 들어가야 할까요? 제가 잊어버렸네요~

**Comment by aanoaa** [comment]
https://duflsdhtwkdahslxj.theopencloset.net/statistics/elapsed 입니다.

**Comment by 10001if** [comment]
@aanoaa 감사합니다. ^^
