### ISSUE TITLE
경과시간 통계

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#32]
- [x] 탈의시간의 평균이 너무 짧은 것 같다 데이터에 이상이 있는지 확인해봐야한다.
- [x] 그날의 방문자수표시
- [ ] ~~y 축을 60분에서 40분으로~~
- [ ] 커서 올리면 수치가 보이도록

**Comment by 10001if** [comment]
형석님 그냥 Y축 두어주세요.

전화로 확인해보니 40분 걸리는 분이 감이지만 20% 가량 있다고 하네요.
바빠지는 상황 좀 더 지켜보고 아무리 바빠도 40분은 넘지 않는 다는 확신이 들 때 다시 말씀드릴게요~!

감사합니다. ^^

-----------------------------------------------------------------

열린옷장
한 만 일 (Man Of Action)
Manil Han

T 070. 4325. 7521
F 02. 6974. 1521
M 010. 6225. 7709
E 10001if@theopencloset.net
H www.theopencloset.net

Address 
서울특별시 광진구 화양동 48-3 웅진빌딩 403호 (우편번호 : 143-917)
#403, Woongjin B/D, 48-3, Hwayang-dong, Gwangjin-gu, Seoul, Korea

**Comment by aanoaa** [comment]
모든 날짜의 데이터가 표시되지 않았는데, 서비스를 재시동하니까
해결되었습니다.

**Comment by aanoaa** [comment]
지난 30일간 탈의상태가 10분이 안되는 주문서가 꽤 있습니다.
1초, 5초 이런것들도 있는데 이건 주문서상태를 변경할때의 실수로
보여집니다.

탈의실 1번으로 했다가 바로 탈의실 2번으로 변경 이런 경우에
잘못계산되어집니다.

한명이 탈의1 + 탈의2 해서 10분이 걸렸다면 10분으로 계산되어야 하는데,

탈의상태1: 5초
탈의상태2: 9분 55초

탈의상태의 평균은 2개에서 10분이니까 5분

이런식으로 계산됩니다.

**Comment by aanoaa** [comment]
탈의하는데 1분 ~ 5분 사이가 40건 정도 됩니다.

탈의 하는데 몇분 이하라면 이 데이터는 실제 탈의시간이 아닐 가능성이
크니까 무시하도록 해야합니다.

@10001if 탈의하는데 최소 몇분이 걸린다고 생각하시나요?
그보다 작은 데이터는 무시하도록 하려합니다.

일단은 탈의상태가 1분이 걸리지 않은 데이터는 무시하도록 하겠습니다.

**Comment by aanoaa** [comment]
> 커서 올리면 수치가 보이도록

이거는 문서에 코드까지 확인했는데 해당하는 옵션을 못찾겠습니다.

**Comment by 10001if** [comment]
4분 이하는 무시해주시면 될 것 같아요~! ^^

나의 iPhone에서 보냄

2015. 2. 2. 오후 12:40 Hyungsuk Hong <notifications@github.com> 작성:

탈의하는데 1분 ~ 5분 사이가 40건 정도 됩니다.

탈의 하는데 몇분 이하라면 이 데이터는 실제 탈의시간이 아닐 가능성이
크니까 무시하도록 해야합니다.

@10001if <https://github.com/10001if> 탈의하는데 최소 몇분이 걸린다고 생각하시나요?
그보다 작은 데이터는 무시하도록 하려합니다.

일단은 탈의상태가 1분이 걸리지 않은 데이터는 무시하도록 하겠습니다.

—
Reply to this email directly or view it on GitHub
<https://github.com/opencloset/monitor/issues/32#issuecomment-72402654>.

**Comment by aanoaa** [comment]
너무 작은 데이터를 지우고 나니까 탈의에 걸린시간이 매일 평균과 30일 평균이 비슷하게 보입니다.
