### ISSUE TITLE
윗배 둘레과 배꼽 둘레 항목 지원

### ISSUE THREAD

**Issue by keedi** [opencloset/monitor#33]
관련 이슈는 다음과 같습니다.

- opencloset/opencloset#372
- opencloset/OpenCloset-Schema#16

기존까지 데이터베이스에 저장한 배 둘레 정보는 사실 윗배 둘레였다고 합니다. 기존 배 둘레였던 `belly`는 `topbelly`로 변경하고 한글로는 윗배 둘레라고 칭하기로 했습니다. 더불어 `belly`는 배꼽 둘레로 칭하기로 했습니다. 시스템에서는 윗배 둘레와 배꼽 둘레 모두 보여야 합니다. 이전에 접근하던 데이터는 `belly`가 아닌 `topbelly`로 접근해야 할 것입니다. :)

**Comment by keedi** [comment]
현재 작업을 처리하기 위해서는 OpenCloset::Schema 0.007 버전이 필요합니다. 설치와 함께 버전을 강제해야 합니다. 더불어 기존 데이터베이스의 경우 opencloset/OpenCloset-Schema#16 이슈에 기록한 질의를 실행해 스키마를 변경해야 합니다.

**Comment by keedi** [comment]
@aanoaa 실서버 데이터베이스에는 이미 반영했으므로 백업본( `~opencloset/backup/db/...` )을 가져오실 경우 굳이 스키마를 변경하실 필요 없습니다.

**Comment by aanoaa** [comment]
`/select` 에서 중동을 윗배둘레로 보여져야 합니다.
`/room` 에서도 마찬가지 입니다.

**Comment by aanoaa** [comment]
배포되었습니다.
