### ISSUE TITLE
/select 화면에서 보여지는 배꼽둘레를 윗배둘레로 변경 요청드립니다.

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#34]
기존 배꼽둘레로 사용하던 정보는 실제로는 윗배둘레였습니다.
이번에 키디님이 수정해주셔서 배꼽둘레 외에 윗배둘레가 추가되었습니다.
현재 저희가 사용하고 있는 사이즈는 윗배둘레이므로 기존의 배꼽둘레 정보가 보여지는 화면은
윗배둘레로 변경 요청드립니다. ^^

**Comment by aanoaa** [comment]
#33 이슈에서 해결되었습니다.
