### ISSUE TITLE
옐로우 레터용 자료 사진 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#35]
옐로우 레터에 들어갈 자료사진을 위해 "꽉찬 모니터 스크린샷"을 요청드립니다.

어제 말씀드린 것 처럼 옐로우레터에 들어갈 자료화면이 필요합니다.

사진은
1. duflsdhtwkdahslxj(대시보드)
2. /room
3. /select

부탁드립니다. ^^

**Comment by aanoaa** [comment]
이게 키와 몸무게같은게 나오는데 블러처리를 해서 드리겠습니다.

**Comment by aanoaa** [comment]
![dashboard 2015-03-02 12-12-42](https://cloud.githubusercontent.com/assets/170528/6434994/4cd2f800-c0d7-11e4-9954-95c65aa8d7e0.png)
![room](https://cloud.githubusercontent.com/assets/170528/6434993/4cd20e18-c0d7-11e4-8121-bd267d0a348c.png)
![select](https://cloud.githubusercontent.com/assets/170528/6434992/4cd10392-c0d7-11e4-811c-9a23121fd0f2.png)

**Comment by aanoaa** [comment]
@10001if 확인하시고 닫아주시거나 의견을 남겨주세요.

**Comment by 10001if** [comment]
@aanoaa 감사합니다~! 잘 사용하겠습니다. ^^
