### ISSUE TITLE
방문자의 예약 시간을 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#36]
![2015-02-27 2 19 17](https://cloud.githubusercontent.com/assets/4696328/6407925/76849fc4-be8d-11e4-9d05-877ab22b11a2.png)
![a](https://cloud.githubusercontent.com/assets/170528/6435051/6a3dbb04-c0d8-11e4-975a-61235abe8150.png)
![b](https://cloud.githubusercontent.com/assets/170528/6435052/6a40876c-c0d8-11e4-9693-a29be4b9b729.png)

의류준비화면에서 탈의실로 변경할 때 혹은 탈의실에서 포장, 수선 상태로 변경할 때
시간표에서 이름을 찾아 변경해야 하는데, 사람이 점점 많아지고 있어서 눈으로 찾기는 힘들고
컨트롤 + F로 찾는데 포장을 하는 화면에서는 코드입력을 위해 영문만을 사용하기도 하고
그렇게 찾는게 생각보다 어렵(?)게 느끼는 분들이 많아서 모니터에서 예약방문시간이 나타나게 해주시길 요청드립니다~ 그렇게 되면 직접 모니터에서 찾아 들어갈 수 있을 것 같습니다. ^^

**Comment by aanoaa** [comment]
@10001if 이곳은 공개된 공간이므로 누구나 열람할 수 있습니다.
개인정보를 노출해서는 안되겠습니다.

**Comment by aanoaa** [comment]
이름과 몸무게등을 흐리게 변환하였습니다.

**Comment by aanoaa** [comment]
서버에 반영하였습니다.

**Comment by 10001if** [comment]
@keedi 깜빡했네요. ㅠ 앞으로 신경써서 올리도록 하겠습니다! ^^

**Comment by aanoaa** [comment]
제가 한말인뎁
