### ISSUE TITLE
이전 탈의실 사용자의 이름을 표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#38]
뭔가 아이디어로 이전탈의실 사용자 이름을 표시해주어야 합니다.
구체적인 방법은 아직 모르겠습니다.

**Comment by 10001if** [comment]
마우스 오버 방식이 좋을 듯 합니다. 클릭을 하면 전 정보와 뒤섞여 혼란스러운 부분이 있을 것 같아요! ^^

**Comment by aanoaa** [comment]
이 기능을 위해서는 탈의실의 이력을 모아둬야 합니다.
monitor 에서는 DB 를 read 만 하고 있기 때문에 이번에도 schema 변경이
없으면 합니다. 해서 `sqlite` 로 간단한 DB 를 만들면 어떻까 싶습니다.
