### ISSUE TITLE
탈의와 의류준비 상태변경 횟수 공유

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#39]
의류 준비화면에서(~/select) 탈의를 2회 이상 사용자에게 최초 탈의실 번호를 표시해줌

현재는 
대여자가 치수측정이 끝나고 의류준비로 넘기면 
'옷창고'에서 옷장지기들이 맞은 옷을 찾아 
탈의실에 넣고 
맞는 탈의실 번호를 선택하여 '탈의 0번'으로 변경합니다.
그리고 대여자가 여러이유로 다른 옷을 원할 경우 
'탈의 0번'이 표시된 상태를 유지한 채 다른 옷을 찾아 건네드립니다.

> 하지만 이 경우 의류준비와 탈의가 혼재되어 시간 측정의 정확도가 떨어지고, 탈의 횟수를 알 수 없다는 이야기를 들었습니다. 따라서 앞으로 모니터에 본 기능을 추가해주시기 요청드립니다. :)

![2015-03-06 11 27 38 3](https://cloud.githubusercontent.com/assets/4696328/6519729/e271c996-c3fb-11e4-94c5-de4b7f6ad20d.png)

이름 아래에
1. 최초 탈의 시 착용했던 탈의실 번호를 노출
2. 탈의가 몇 번째인지 보여주기
(의류준비 횟수로 탈의를 계산해 주시면 될 것 같은데, 문제가 있다 싶으시면 말씀해주세요 ^^)
> ex) 치수측정 - 의류준비 - 탈의 - 의류준비 (이 경우는 탈의 2회)

치수측정 - 의류준비 - 탈의 - 의류준비 - 탈의 - 의류준비 - 탈의 - 포장 - 결제대기 - 대여 중

정리하자면 기존에는 의류준비 뒤 탈의 포장으로 진행이 되었다면 
앞으로는 옷장지기들이 탈의 시에는 의류준비 항목으로 매번 변경할 것입니다.
이때 의류준비 화면 모니터에서 최초 탈의자와 2회 이상 탈의자의 정보가 섞여 혼동을 줄 가능성이 있다고 판단되는 부분이 있으므로, 이상의 두 가지 정보를 표시해주시길 부탁드립니다. ^^

**Comment by aanoaa** [comment]
제가 알고있는 현재 진행순서는

    의류준비 -> 탈의01 (상태는 안바뀌고 옷을 계속 골라주고 입어봄) -> 수선 이나 포장

인데

    의류준비 -> 탈의01 -> 의류준비 -> 탈의03 -> 의류준비 -> 탈의05 -> 수선 이나 포장

이런식으로 탈의실도 바뀌는 건가요?
이건 직접 설명을 들어보는게 좋을 것 같습니다.

**Comment by aanoaa** [comment]
탈의에서 의류준비로 바뀌었을때 

- 몇번째 옷을 준비하는 건지 표시
- 몇번 탈의실을 이용했는지 표시


의류준비에서 탈의로 바뀌었을때 

- 몇번째 옷을 입는 건지 표시

**Comment by aanoaa** [comment]
탈의실이 변경되지는 않을 것 같다고 합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2015-03-18 11-34-44](https://cloud.githubusercontent.com/assets/170528/6701729/0a5ef836-cd64-11e4-8ee9-bb8b57c7feec.png)

`#4` 이게 탈의실 번호고요 `3` 이 이용횟수 입니다.

4번 탈의실 3번 이용했음이란 뜻입니다.

**Comment by aanoaa** [comment]
실섭에 적용했습니다.
많이 바뀌어서 내일 하루 모니터링 해봐야 합니다.
@10001if 혹시 문제가 생기면 전화로 바로 알려주세요.

**Comment by 10001if** [comment]
@aanoaa 제가 내일 오전 오후 계속 외부에 있을 것 같아요. 그래도 오전에 하남 세탁소 다녀와서 사무실에 들어오는 시간이 있으니 한번 체크해복겠습니다 ^^
