### ISSUE TITLE
낮은 해상도에서 볼 수 있는 화면 디자인

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#44]
의류준비와 탈의실 화면에서 

얼추 가로가 650 정도? 화면에서 두개의 화면을 하나의 모니터에서 보고 싶어합니다.

여러 해상도에서 알마게 표현되도록 디자인 수정이 필요합니다.

이것이 그 힙하다는 반응형 웹디자인

**Comment by aanoaa** [comment]
@10001if 실제 사용하려하는 모니터의 해상도가 어떻게 되나요?

**Comment by 10001if** [comment]
키디님 혹시 알고 계시면 이야기 해줄 수 있으세요?
형석님 어제 키디님이 보고 가셨거든요 ^^

————————————————————————————————

“You must be the change you want to see in the world.” 
―Mahatma Gandhi

열린옷장
한 만 일 (Man Of Action)
Manil Han

T 070. 4325. 7521
F 02. 6974. 1521
M 010. 6225. 7709
E 10001if@theopencloset.net
H www.theopencloset.net

Address 
서울특별시 광진구 화양동 48-3 웅진빌딩 403호 (우편번호 : 143-917)
#403, Woongjin B/D, 48-3, Hwayang-dong, Gwangjin-gu, Seoul, Korea

**Comment by aanoaa** [comment]
@10001if 아 외부에 계신거면 제가 올라가서 확인해보겠습니다.

**Comment by aanoaa** [comment]
좌측부터

- `1360x768`
- `1920x1080`
- `1280x1024`

입니다.

> 얼추 가로가 650 정도

라고 하셨으니까 `1360x768` 에서 잘 보여야 합니다.

**Comment by aanoaa** [comment]
firefox 에서 `Ctrl + Shift + M` 을 눌러서 원하는 해상도로 볼 수 있습니다.

**Comment by aanoaa** [comment]
`1360x768` 을 기준으로 봤을때 아래와 같이 보입니다.

![screenshot-localhost 5000 2015-04-08 11-57-02](https://cloud.githubusercontent.com/assets/170528/7038048/c5d43e4a-dde6-11e4-8786-bcc285a2c3ae.png)
![screenshot-localhost 5000 2015-04-08 11-57-47](https://cloud.githubusercontent.com/assets/170528/7038049/c5d5d354-dde6-11e4-9e95-5f11b4568afa.png)

**Comment by aanoaa** [comment]
의류준비와 탈의실을 스크롤없이 동시에 보여주는건 어려울 것 같습니다.
글씨가 너무 작아져요.

**Comment by aanoaa** [comment]
탈의실에서

- comment
- size

를 없애고 크기를 줄여서 한눈에 볼 수 있게 해달라고 합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2015-04-08 15-38-48](https://cloud.githubusercontent.com/assets/170528/7040091/9fe9e076-de05-11e4-85e8-0c340c6de1f0.png)

위처럼 해보았읍니다.

@10001if 의견을 남겨주세요.

**Comment by aanoaa** [comment]
@10001if said..

> 그런데 왼쪽의 의류준비 화면이 실시간 적용이 안된다고 해서요

**Comment by aanoaa** [comment]
제 맥부기에서 monitor app 이 돌지 않습니다.
SQLite 관련 에러입니다. `history` 테이블이 없다고 하는데 뻥같고 대소문자 이슈가 아닌가 싶습니다.

**Comment by aanoaa** [comment]
라이브러리 PATH가 안잡혀있었던걸로 기억합니다.
해결되었습니다.
