### ISSUE TITLE
preparation 에서 드래그 & 드롭으로 상태변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#46]
의류준비 <-> 탈의실 간의 상태변경을 더 직관적으로 쉽게 할 수 있을 것 같습니다.

**Comment by aanoaa** [comment]
우와 드래그앤드롭 졸 어려움

**Comment by aanoaa** [comment]
마우스 우클릭(Context Menu)에 몇가지 메뉴를 넣어서 드래그앤드랍 대신 활용하면 어떨까 합니다.
http://medialize.github.io/jQuery-contextMenu/demo.html

- to 탈의1 ~ 탈의11
- to 수선
- to 의류준비
- to 포장

이렇게 하면 monitor 에서 적절한 상태변경을 활용할 수 있겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/470

이슈가 우선 적용되고 배포되어야 합니다.

**Comment by aanoaa** [comment]
드래그앤드랍이면 좋겠지만, 애니메이션 효과라던지, 영역계산이라던지 하는 처리가 더 시간이 걸립니다.

잘만들어진 라이브러리를 사용하면 시간을 단축할 순 있겟지만, 처음부터 드래그앤드랍을 고려해서 레이아웃부터 다시 잡아야합니다.

졸 어렵기 때문에 일단 우클릭메뉴(ContextMenu) 를 사용해보는 것이 효율적이겠습니다.

**Comment by keedi** [comment]
꼭 필요한 것이 아니라면 드래그앤드롭 비추에 한표입니다. :)

**Comment by aanoaa** [comment]
배포하였습니다.

**Comment by aanoaa** [comment]
망함 윈도우즈 파폭에서는 우클릭 안됨 ㅋ

**Comment by aanoaa** [comment]
윈도우즈의 문제가 아닙니다.
배포환경에 문제가 있어 보입니다.

왜 안되는지 탐구생활을 해봐야 합니다.

**Comment by aanoaa** [comment]
$ npm install -g coffee-script

배포환경에 `coffee` 를 사용할 수 있도록 해야합니다.

**Comment by aanoaa** [comment]
`silex` 계정으로 설치하고

    $ ndenv rehash

해주었습니다.

**Comment by aanoaa** [comment]
`ubic/monitor` 설정에 아래 환경변수를 추가하였습니다.

    RBENV_VERSION        => '2.1.4',
    NDENV_VERSION        => 'v0.11.14',
    RBENV_ROOT           => '/opt/anyenv/envs/rbenv',
    ANYENV_ROOT          => '/opt/anyenv',
    NDENV_ROOT           => '/opt/anyenv/envs/ndenv',

**Comment by aanoaa** [comment]
정상적으로 동작합니다.
윈도우즈에서 동작하는지 확인해야 합니다.

**Comment by aanoaa** [comment]
윈도우즈에서도 동작합니다.

**Comment by aanoaa** [comment]
우클릭 메뉴의 색이 잘 안보입니다. 변경해야 합니다.

**Comment by aanoaa** [comment]
색상 변경하고 배포하였습니다.

**Comment by aanoaa** [comment]
의류준비 -> 포장, 수선으로의 상태변경 메뉴가 필요합니다.
