### ISSUE TITLE
의류 준비에서 수선으로 변경시 치수 측정 상태로 변경됨

### ISSUE THREAD

**Issue by keedi** [opencloset/monitor#52]
항상 그런지는 아직 모르겠으나 어제 보고 이후 오늘 또 해당 증상이 있었다고 합니다. 의류 준비에서 수선으로 변경을 했는데 갑자기 사라지면서 시간표에서 확인했더니 해당 주문서가 치수 측정 상태로 바뀌었다고 합니다. 동시에 사용한 가능성은 없는 것이 오늘 오전 1명이 사용하면서 발생했다고 합니다.

**Comment by keedi** [comment]
아마도 로그 확인 및 분석이 필요할 것 같습니다.

**Comment by 10001if** [comment]
오늘 오전에 동 상황이 발생한 사용자의 번호는 16530 입니다.

**Comment by aanoaa** [comment]
17:30 박성한 의류준비 -> 수선 했는데 치수측정으로 바뀜

**Comment by aanoaa** [comment]
맞습니다.
현재 의류준비에서 `수선` 으로 누르면 모두 `치수측정` 으로 변경됩니다.
오타 혹은 상태번호를 잘못 알았던 것 같습니다.

**Comment by aanoaa** [comment]
점심시간에 맞춰서 배포하겠습니다.
