### ISSUE TITLE
베스트핏 입력하는 과정 중 "잘모름" 버튼 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#55]
베스트핏을 쉽게 입력할 수 있게 되면서 기존 시간표에서 입력하던 것과는 비교를 할 수 없게 편해졌습니다. 그런데 제가 직접 사용해보다보니 아쉬운 점이 발생했는데요.

1. 소봉이가 마지막 입은 의류를 체크하고 베스트라고 생각하여 베스트 핏을 입력.
2. 방문했을 때 입었던 원래 옷으로 갈아입는 중에 그 사이 소봉이는 다른 분의 의류를 체크하게 되었음
3. 포장이 필요한 옷을 마닐이 받아 포장을 실시하려고 포장버튼을 클릭
4. 이때 베스트 핏인지를 묻는 화면이 나오는데. 마닐은 베스트인지 모름. 그래서 마닐은 보통으로 누름
5. 대여자분은 베스트 핏이었지만 마닐이 보통으로 누르는 바람에 보통으로 변경됨

그래서 혹시 "잘모름" 버튼을 누르면 베스트 핏인 경우 그대로 베스트 핏으로 진행되도록 할 수 있을까요?

- 생각해보면 포장을 누르는 순간 왼쪽에 색깔이 노란색인지 확인하고 진행하면 되겠지만, 이게 잘 안되는 것 같습니다. ^^;

**Comment by aanoaa** [comment]
대신에 버튼에 현재상태를 강조해서 표시합니다.

**Comment by 10001if** [comment]
들으셨다고 들었지만, 한번 더 말씀드려요~ 강조된 현재 상태가 잘 보이지 않는다고 하네요. 저도 봤는데 잘 안보이더라구요. 분명하게 확인 가능하도록 수정 요청드립니다. ^^

**Comment by aanoaa** [comment]
수정해서 배포되었습니다.
