### ISSUE TITLE
의류준비 중인 사람을 클릭하면 나타나는 네모박스의 색상을 노란색으로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#56]
현재는 네모박스가 흰색실선으로 나타나는데, 노란색 두꺼운 선(현재 선의 2배 두께면 좋겠습니다.)으로 표시되도록 부탁드립니다. 현재 실선은 "내가 의류를 찾고 있으니 다른사람은 아래에 나타나는 의류준비의 옷을 찾아라~!"로 활용하고 있는데, 멀리서 보면 실선이 조금 구분하기 힘들다는 의견이 있어 수정을 요청드립니다.

**Comment by aanoaa** [comment]
아직 배포되지 않았습니다.
