### ISSUE TITLE
대시보드 화면에서 의류준비-탈의가 여러번 이뤄지는 경우 한번만 화면에서 보여주기

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#57]
최초에는 일반적인 경우 의류준비-탈의가 1번만 일어났습니다.
하지만 현재는 의류준비-탈의-의류준비-탈의가 6~7번 일어나는 경우도 있습니다.

대기실에서 대여자분들은 대시보드 화면을 보고 있는데.
여러명이 탈의실과 의류준비 상황을 오다가보면 대기하는 자신의 이름을 확인하기가 어려운 상황이 종종 생깁니다.

탈의실에서 다른 옷을 요청하시는 대여자는 실제로 대기실에 있지 않고 탈의실에 머물러 있습니다.
따라서, 대기실에 앉아있는 대여자들은 탈의중이었다가 의류준비 중인 다른 사람들의 상황을 실시간으로 확인하지 않아도 됩니다. 대기실 화면에서는 탈의-의류준비 상황을 계속해서 보지 않을 수 있도록 수정을 하고 싶습니다.

**Comment by aanoaa** [comment]
소리만 안나는게 좋을까요 아니면 계속 탈의에 머물러 있다가 의류준비 이외의 상태로 변경되면 변경된 상태로 이동시키는게 좋을까요?

**Comment by aanoaa** [comment]
이따가 시간나시면 제자리에서 확인해보시고 말씀해주세요.
