### ISSUE TITLE
수선 화면

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#58]
수선 상태인 사용자들의 목록이 표시된 화면이 필요합니다.

**Comment by aanoaa** [comment]
머지되었지만 바지길이를 넣어줘야 합니다.

**Comment by 10001if** [comment]
수선화면도 실시간으로 동기화되었으면 좋겠습니다. 수선을 넘기고 이슈가 달라지는 경우가 있기 때문입니다. ^^

**Comment by aanoaa** [comment]
실시간으로 동기화 되고 있습니다.

**Comment by 10001if** [comment]
@aanoaa 그랬군요~! 감사합니다. ^^

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2015-10-23 12-02-50](https://cloud.githubusercontent.com/assets/170528/10683551/184ab310-797e-11e5-90db-882f02f7c27c.png)

**Comment by aanoaa** [comment]
상태는 5층에서 의류준비하시는 분이 변경하는 건 알겠는데, 수선길이는 누가 어디에서 입력하나요?

**Comment by aanoaa** [comment]
수선화면에 남자는 파랑 여자는 빨강으로 현재 상태의 숫자를 보고 싶습니다.
    
    | 대기중 4 (2/2) | 치수측정 1 (1/0) | 의류준비 7 (2/5) | 탈의(0/0) | 수선(0/0) | 포장(0/0) | 결제대기(0/0)

**Comment by aanoaa** [comment]
`상세 대여 목적` 또한 나타내야 합니다.

**Comment by aanoaa** [comment]
9753612

**Comment by 10001if** [comment]
수선화면에 남자는 파랑 여자는 빨강으로 현재 상태의 숫자를 보고 싶습니다.
| 대기중 4 (2/2) | 치수측정 1 (1/0) | 의류준비 7 (2/5) | 탈의(0/0) | 수선(0/0) | 포장(0/0) | 결제대기(0/0)

본 화면이 다림질 하는 부분에서 보면 크기가 작아서 잘 보이지 않는다고 합니다.

수선을 하는 사람이 3명이상 쌓이는 경우가 많지 않습니다. 
그래서 상단의 글씨 사이즈를 2배로 키워주셨으면 좋겠습니다~ 
그리고 여성 남성의 구분이 색상으로는 어렵다고 하네요. 숫자 옆에 남성/여성 아이콘을 넣어 표시해 주실 수 있을까요?

**Comment by aanoaa** [comment]
![screenshot-duflsdhtwkdahslxj theopencloset net 2015-11-17 13-14-19](https://cloud.githubusercontent.com/assets/170528/11202608/2d5fe7e4-8d2d-11e5-9634-c7a20d563a4d.png)

**Comment by aanoaa** [comment]
지금 안건데, 수선화면에서의 현황판에서는 22:00 예약자가 포함되어 있습니다.

**Comment by aanoaa** [comment]
남자, 여자를 숫자로 적지말고 아이콘으로 표시되면 좋겠다고 합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2015-11-19 12-05-01](https://cloud.githubusercontent.com/assets/170528/11261227/cfe5ed36-8eb5-11e5-9d95-a4e62c2f6da5.png)
