### ISSUE TITLE
whitelist IP 주소 인증

### ISSUE THREAD

**Issue by neofu** [opencloset/monitor#6]
서브도메인으로 접속을 한정하기에 한계가 있기에,
사일렉스 IP 1개, 열린옷장 IP 2개, 총 3개의 IP만 접속이 되게 하여야 합니다.
열린옷장 IP는 면담으로 전달합니다.

**Comment by aanoaa** [comment]
이거 설정이 잘못되어있습니다.

**Comment by aanoaa** [comment]
$ cpanm --installdeps .

으로 의존성을 우선 해결해주어야 합니다.

**Comment by aanoaa** [comment]
@MoDoLEE 님이 맥어드레스 인증할 수 없냐고 물어봤습니다.

**Comment by aanoaa** [comment]
local area network 밖에서는 알아낼 방법이 없으므로 패스합니다.
