### ISSUE TITLE
의류준비에서 바지길이를 입력할 수 있도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#63]
default: 90
90 ~ 120

    <<    90    >>

좌우로 누르면 커졌다가 줄었다가 함

**Comment by aanoaa** [comment]
그거를 bestfit 입력 밑에다가 넣는다.

**Comment by aanoaa** [comment]
2단위로 90 ~ 110 까지 선택할 수 있도록 한다.

**Comment by aanoaa** [comment]
`비어있음` 도 있어야 한다.

**Comment by aanoaa** [comment]
반반 나눠서 표시하고 바지길이 글자 크기를 좀 더 크게 해달라는 의견이 있습니다.

**Comment by aanoaa** [comment]
위에서 보니까 수선을 위한 팬츠길이를 90, 96 이런식으로 얘기하는게 아니라
+4, -3 이런식으로 얘기하던데, 실제 사용하는 단위를 쓰지 않으면 무쓸모가 아닐까여?

**Comment by 10001if** [comment]
@aanoaa 아닙니다~ -3, +4 이렇게 작성하고 포장대 위에서 다시 바지길이를 재서 입력하려고 합니다. 아직 정착되지는 않았지만, 필요한 과정이라고 생각하고 있어서 수선, 포장 전에 입력하도록 포로세스를 조정할 계획입니다. ^^

**Comment by aanoaa** [comment]
바지길이가 주문서에 입력되는데, 이게 사용자의 바지길이로 입력되도록 한다
주문서 + 사용자정보를 갱신해주도록 합니다.

**Comment by aanoaa** [comment]
처음에 보여줄때에 주문서의 팬츠길이가 없으면 사용자의 팬츠길이를 보여주도록 해야 의미가 있을 것 같습니다.
