### ISSUE TITLE
수선완료 기능

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#66]
4층 화면에서 수선이 완료되면 대여자를 클릭하여 수선이 완료됨을 표시해주고
5층에서도 동일하게 수선이 완료됨을 나타낼 수 있으면 좋겠습니다.

현재는 5층에서는 수선이 완료되었는지 여부를 확인하기가 어렵기 때문입니다.
돌아오시면 다시 인사드리고 설명 드릴게요. ^^

**Comment by aanoaa** [comment]
repair 에서 뭔가를 하면 수선이 완료되었다는 정보가 preparation 에 나타나야합니다.

**Comment by aanoaa** [comment]
의류준비에서 깜빡깜빡하면 안놓칠것 같다는 의견
감사합니다.

**Comment by aanoaa** [comment]
`repair` 에서 완료하면 잘 안바뀝니다.

**Comment by aanoaa** [comment]
코드상에선 문제가 없어보이는데, 일단 보류합니다.

**Comment by 10001if** [comment]
나중에 현장에서 직접 확인 부탁드립니다~ 실제로 사용해보면 잘 적용이 되지 않는 것 같습니다.

**Comment by aanoaa** [comment]
상태 변경후에 중복되어서 라벨이 변경되던 문제점을 해결하였다고 믿습니다.
