### ISSUE TITLE
온라인 대여자에 대한 상태표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#70]
임시방편입니다.
온라인은 22:00 에 몰아서 하고있습니다.
22:00 예약건은 dashboard 에 표시가 안되어야 합니다.

**Comment by keedi** [comment]
다음 이슈와 연관이 있습니다.

- opencloset/opencloset/issues/552
- opencloset/OpenCloset-Schema/issues/27
- opencloset/monitor/issues/70

**Comment by aanoaa** [comment]
현황판에서만 보이지 않도록 작업하였습니다.
