### ISSUE TITLE
의류준비화면에서 기존에 대여했던 대여기록들이 4번까지 나타나도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#76]
의류준비 중인 상태에서 재방문인 경우 기존의 대여기록이 나타나는데, 이 때 기록이 최근이 아니라 맨 처음 빌린 품목으로 뜬다고 하네요. 여러번 대여하는 경우가 있어서 가장 최근 기록이 맨 처음에 보이고 그 전 그 전전 기록이 순서대로 4번까지 보였으면 좋겠습니다. 이건 뵙고 다시 설명드릴게요.

**Comment by aanoaa** [comment]
피드백을 받아서 반영하겠습니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2015-11-21 17-48-47](https://cloud.githubusercontent.com/assets/170528/11317651/43469d66-9078-11e5-86c7-06e9731fc0a6.png)

**Comment by aanoaa** [comment]
기증자, 의류상태, 색상등에 대한 정보는 마우스를 가져다가 올리면 보이도록 하였습니다.

**Comment by aanoaa** [comment]
사이즈도 표시해주어야 합니다.

**Comment by aanoaa** [comment]
의류기록을 역순으로 봤으면 좋겠다고 합니다.

**Comment by aanoaa** [comment]
짬됐습니다.
