### ISSUE TITLE
온라인 대여자에 대한 현황판 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#79]
수선이랑 비슷하게 보이도록

- 상태
- 이름
- 입금여부를 상태와 별개로 toggle 가능 하도록

**Comment by aanoaa** [comment]
문자보내는 링크를 같이 보여줍니다.

**Comment by aanoaa** [comment]
`monitor.conf`

```
my $SMS_FROM = '07043257521';
    sms_from => $SMS_FROM,
```

설정파일에 `sms_from` 이 필요합니다.

**Comment by aanoaa** [comment]
배포전에

    $ bower install

해줘야합니다.

**Comment by aanoaa** [comment]
@10001if 주소는 `/online` 입니다.
온라인 대여자 현황을 볼 수 있고 SMS 정도 보낼 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 네! 주소 확인했고 온라인 담당자분께 전달해 드렸습니다. 피드백이 오는대로 다시 문의드리도록 하겠습니다. ^^
