### ISSUE TITLE
온라인 사용자의 현황이 여전히 대기자 목록에 나타남

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#81]
22:00 은 보이면 안됨

포장상태에서 나타나고 있습니다.
결제대기도 확인해봐야 합니다.

**Comment by aanoaa** [comment]
@10001if 사진 찍어놓으신 거에서 대여자분의 이름을 알려주세요.
좀 찾아봐야 합니다.

**Comment by 10001if** [comment]
12월 30일이구요. 윤영중, 최병민, 권순만, 홍민지, 신은지, 백수연 입니다.

**Comment by aanoaa** [comment]
12월 30일이면 future?

**Comment by 10001if** [comment]
11월 30일입니다.

**Comment by aanoaa** [comment]
dd4d111dcebd96b6c5a430207fbf333b5ea78ea5

수정하였습니다.
