### ISSUE TITLE
대시보드 화면 하단에 광고문구를 삽입

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#85]
대기실 대쉬보드 밑부분 활용하여 광고문구를 삽입하고자 합니다.  

1. 오늘 (00일) 대여하시면 반납일은 00일(0요일)입니다.   
2. 기증자의 소중한 마음이 담긴 옷과 구두이오니 소중히 입고 깨끗하게 돌려주세요.

관련 내용이 확실히 결정되면 다시 올리도록 하겠습니다.

**Comment by 10001if** [comment]
대여기간안내
대여일 12월 10일(목) - 반납일 12월 13일 (일) 
* 반납일이 일요일인 경우는 월요일 반납
* 택배 반납은 반납일 1일전 발송 

오늘 대여하신 옷과 구두에는 기증자의 마음이 담겨있습니다. 소중히 입고 깨끗하게 반납 부탁드립니다.

**Comment by 10001if** [comment]
문구 이렇게 올려주심 됩니다~ ^^

**Comment by 10001if** [comment]
하단에 올리려면 약간 보기좋게 해야 할 것 같은데~ 우선 올려서 보여주시면 다음 주에 제가 옆에서 보면서 바로 수정을 부탁드릴게요~ 조금 덜 예뻐도 이해하는데 도움을 드릴 수 있으면 바로 해봐도 좋을 것 같아요~ ^^

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2015-12-14 18-01-04](https://cloud.githubusercontent.com/assets/170528/11776714/b3fb6a0c-a28c-11e5-9d86-d0a5f4a52e88.png)

**Comment by aanoaa** [comment]
일요일 을 일요일/공휴일 로 바꿨습니다.

**Comment by aanoaa** [comment]
대여 반납일 글자 크기를 두배정도로 키워달라고 하십니다.

**Comment by aanoaa** [comment]
5fa1bfbc1dfb1eba83ddbdf94e7875b6dead0236

**Comment by aanoaa** [comment]
젤 아래 설명 글자 폰트도 크게 해야합니다. `2em`

**Comment by aanoaa** [comment]
대여일 반납일을 staff 가 수정할 수 있으면 좋겟다고 합니다.

**Comment by 10001if** [comment]
반납일이 일요일/공휴일인 경우는 다음날 반납 
택배 반납은 반납일 1일전 발송
오늘 대여하신 옷과 구두에는 기증자의 마음이 담겨있습니다. 소중히 입고 깨끗하게 반납 부탁드립니다.

-->>
반납일이 일요일/공휴일인 경우는 다음날 반납 
택배 반납은 반납일 1일전 발송

오늘 대여하신 옷과 구두에는 기증자의 마음이 담겨있습니다. (한 칸 내려서) 
소중히 입고 깨끗하게 반납 부탁드립니다. 

이 문구의 크기를 2배로 키워주시면 좋겠습니다~ (대여기간 안내 문구보다는 작게.. ^^:)

3번째 줄에 앉아서 살펴보니 이 문구가 잘 안보이더라구요. ^^

**Comment by aanoaa** [comment]
> 대여일 반납일을 staff 가 수정할 수 있으면 좋겟다고 합니다.

를 해결하지 않고 닫았습니다.

**Comment by aanoaa** [comment]
반납일을 클릭하면 달력이 나오고 거기서 반납일을 선택하면 됩니다.

@10001if 지금은 제가 적용시켜놓았으니 대기실 화면 새로고침 한번만 해주세요.

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2015-12-17 10-34-19](https://cloud.githubusercontent.com/assets/170528/11858971/c91e5d12-a4a9-11e5-8050-879c4bf629b2.png)

**Comment by 10001if** [comment]
방금 확인완료하였습니다! 감사합니다! ^^

**Comment by 10001if** [comment]
그런데 하단문구를 좀 더 키워야 할 것 같아요. 오시면 직접 뵙고 설명드릴게요 ^^

**Comment by 10001if** [comment]
@aanoaa 반납일 지정하는게.. 별거 아니라고 생각하셨을지 몰라도~ 휴일에 반납일이 끼어 문의하는 분도 종종계시고 왜 그렇게 되는지, 연장시 일요일이 있으면 왜 그건 안빼주는지 등등 일일이 설명하기 어려운 부분들이 있었는데, 컴퓨터에 표시되니 뭔가 더 정확하고 공정성 있게 느껴집니다. 아마도 그런 것 때문에 5층 식구들이 좋아한 것 같아요. 정말 감사합니다. ^^

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2015-12-17 16-48-49](https://cloud.githubusercontent.com/assets/170528/11864227/20de38e0-a4de-11e5-881e-9c0ed2cf0665.png)

다른 글씨를 키우니까 반납일이 강조가 안되서 색상을 넣어봤습니다.

**Comment by 10001if** [comment]
와우! 아주 좋네요~ 시원시원하고~ 좋습니다. 색상이 바뀐다는 생각을 못했어요~ 그 날 생일이신 분은 이름을 노란색으로 바꿔드릴까 하는 생각을 잠시 해보았습니다. ㅎㅎ

**Comment by aanoaa** [comment]
e9a211046036f9b62e1306ba0bde82535e65a9ae

**Comment by aanoaa** [comment]
local timezone 을 적용해야 합니다.

**Comment by aanoaa** [comment]
어라 되어 있는데..

**Comment by aanoaa** [comment]
https://metacpan.org/pod/DateTime#DateTime-now

> This class method is equivalent to calling from_epoch() with the value returned from Perl's time() function. Just as with the new() method, **it accepts "time_zone" and "locale" parameters.**

**Comment by aanoaa** [comment]
ec99e4ae5ec33c7bcd3dcb07a3b3ff9d2b31a31f 개발은 되어 있는데 배포가 안되었던 것 같습니다.

**Comment by aanoaa** [comment]
배포하고 확인하였습니다.
