### ISSUE TITLE
대시보드/online 화면에서 문자 매크로를 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#92]
1. 온라인 배송 후 안내 (첫대여) 
[열린옷장] CJ대한통운/1234-1234-1234 반납 시, 설문지와 함께 받은 상자에 담아 보내주세요^^

2. 온라인 배송 후 안내 (재대여)
[열린옷장] CJ대한통운/2021-4884-2021, 택배 반납 시, 12/24에 받은 상자에 담아 보내주세요^^

3. 온라인 입금 안내
[열린옷장] 대여 금액 00000원,금일 오후 1시까지 입금해주세요. 국민은행 205737-04-003013 열린옷장/시간내 미확인시 자동 취소됩니다.

4. 온라인 자동 취소 고지
[열린옷장] 000님 금일 오전까지 미확인시 발송 취소 됨을 알립니다.
 
5. 온라인 사전 안내 
 [열린옷장] 000님 온라인신청 확인되었습니다. 12/24 발송 예정이며, 자세한 사항은 12/23 문자 안내 드리겠습니다. 감사합니다^^

**Comment by aanoaa** [comment]
adbc18f310cb8ac463c3b22afd98dddcb38ed81e

**Comment by aanoaa** [comment]
발신 번호가 바뀌어야 합니다.

    070-7583-7521

**Comment by keedi** [comment]
ㅎㄷㄷ 모니터에서도 문자를 보내고 있었다니...

**Comment by aanoaa** [comment]
이메일로 kth 담당자한테 발신번호등록을 요청했습니다.

**Comment by aanoaa** [comment]
등록되었고 변경했습니다.

**Comment by aanoaa** [comment]
문자 메세지중에 `12/23`, `12/24` 로 되어 있는게 거슬렸고, 메세지도 좀 이상합니다.

오늘 12/28 일을 기준으로 봤을때,

    [열린옷장] 000님 온라인신청 확인되었습니다. 12/24 발송 예정이며, 자세한 사항은 12/23 문자 안내 드리겠습니다. 감사합니다^^

위 메세지가 아래처럼 바뀌는건 어떤가요?
오늘 + 1일

    [열린옷장] 000님 온라인신청 확인되었습니다. 12/29 발송 예정이며, 자세한 사항은 문자 안내 드리겠습니다. 감사합니다^^


이것도 좀 이상합니다.

    [열린옷장] CJ대한통운/2021-4884-2021, 택배 반납 시, 12/24에 받은 상자에 담아 보내주세요^^

요건 어떤가요?

    [열린옷장] CJ대한통운/2021-4884-2021, 택배 반납 시 받은 상자에 담아 보내주세요^^

정리하면,

    온라인 배송 후 안내 (첫대여)
    [열린옷장] CJ대한통운/1234-1234-1234 반납 시, 설문지와 함께 받은 상자에 담아 보내주세요^^

    온라인 배송 후 안내 (재대여)
    [열린옷장] CJ대한통운/2021-4884-2021, 택배 반납 시, 받은 상자에 담아 보내주세요^^

    온라인 입금 안내
    [열린옷장] 대여 금액 00000원,금일 오후 1시까지 입금해주세요. 국민은행 205737-04-003013 열린옷장/시간내 미확인시 자동 취소됩니다.

    온라인 자동 취소 고지
    [열린옷장] 000님 금일 오전까지 미확인시 발송 취소 됨을 알립니다.

    온라인 사전 안내
    [열린옷장] 000님 온라인신청 확인되었습니다. 12/29 발송 예정이며, 자세한 사항은 문자 안내 드리겠습니다. 감사합니다^^

**Comment by aanoaa** [comment]
@10001if call me

**Comment by aanoaa** [comment]
저는 필요한 것 같은데 진행이 없으니 닫겠습니다.
