### ISSUE TITLE
결제시 확인을 할 수 있는 모니터를 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#93]
오늘 오전 회의시 이슈가 발생하여 문제를 해결할 수 있는 방법을 고민하다가 우선 이슈에 등록합니다.

저희가 의류를 대여할 때 현장에서 바로 입고 가시는 경우가 있습니다. 그 비율은 10~15% 정도 되는데요. 이런 경우에는 저희가 의류를 확인하여 (입고 있는 옷의 코드를  찾아) 포장완료상태로 바꿉니다. 

일반적인 포장완료 상태의 경우에는 포장된 의류가 결제란에 도착해 있으므로 결제하는 분은 주문서 화면에서 포장완료상태를 새로고침하여 결제를 시도합니다. 하지만 바로 입고 가시는 경우에는 의류가 도착해 있지 않으므로 결제자는 결제를 해야 한다는 인식을 하지 못합니다. 

따라서, 포장완료의 상태가 실시간으로 전송되는 방법이 있어야 하는데. 이 방법이 어렵다는 이야기를 지난 번에 들은 적이 있어서 모니터 화면으로 해결할 수 없을까 하여 이슈로 등록합니다. 모니터가 실시간 전송이 된다면 포장완료 상태의 사람을 따로 볼 수 있을 것 같습니다. 본 이슈는 여쭤보고 진행하는 것이 좋을 것 같습니다. 우선 등록해 놓겠습니다. ^^

**Comment by aanoaa** [comment]
주문서의 포장완료 목록이 실시간으로 갱신되어야합니다.
