### ISSUE TITLE
대여가능 의류 제안

### ISSUE THREAD

**Issue by aanoaa** [opencloset/monitor#94]
https://github.com/opencloset/opencloset/issues/627

위 이슈는 사용자의 신체치수를 가지고 대여가능한 의류를 제안해주는 기능입니다.
이 기능을 모니터에서 사용하고 싶은데, 문제는 복잡한 연산이 많아서 응답시간이
길다는 것입니다.

요청하고 결과를 받은후에 어찌할 수 있도록 비동기 처리가 필요합니다.

일단 오리지날 이슈과 완료되고 나면 모니터쪽에 붙이도록 합니다.

cc @yongbin

**Comment by yongbin** [comment]
https://github.com/opencloset/opencloset/issues/627 , https://github.com/opencloset/opencloset/pull/677에 준비가 모두 끝났습니다. 진행해주시면 됩니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/800

**Comment by aanoaa** [comment]
의류준비화면은 js 쪽이 너무 복잡합니다.

- 웹소켓을 활용한 실시간 이벤트 처리
- 웹소켓을 활용한 동기화
- 다양한 액션에 대응한 변경 및 동기화
- 다양한 이벤트 알림에 대응한 변경 및 동기화

여기에 맞춤의류에 대한 기능을 넣으면 관리가 힘들어 질 것 같습니다.
5벌정도의 맞춤의류를 주문서마다 보여줘야 하는데, 동기화 되어야 하고 여러 상황에 맞게 큐에 넣어야 합니다.
큐에 넣었던 작업이 완료되면 DOM 을 생성해서 각 주문서별로 보여주어야 하고 이를 동기화 해야 합니다.

해서, 좀 더 확장 가능한 형태로 현재의 기능을 변경하고 이후에 맞춤의류 기능을 붙이도록 하겠습니다.

**Comment by aanoaa** [comment]
- 의류준비별로 새로고침을 할 수 있어야 함
- 탈의실전체를 새로고침 할 수 있어야 함
- 의류준비 전체를 새로고침 - 또는 의류준비목록에 추가 할 수 있어야..
- 수선목록을 새로고침
- 포장목록을 새로고침

js 쪽에서는 DOM 을 다룰 것이 아니라 주문서 번호별로 html 을 받아서 새로고침

아이디어로는 이런식이면 좀 해볼만 하지 않나 싶습니다.

주의할 것이 `hypnotoad` 의 워커가 여러개인 환경에서 개발되어야 합니다.

**Comment by aanoaa** [comment]
부분적으로 새로고침할 수 있도록 구조를 변경하였습니다.
이제 큐에넣어서 작업돌리고 작업이 완료되고나면 화면을 갱신해주면 될 것 같습니다.

**Comment by aanoaa** [comment]
재고관리의

    GET /user/:id/search/clothes

에 대해서 json 으로 데이터를 받을 수 있도록 해야
필요한 데이터를 골라서 다시 나타낼 수 있을 것 같습니다.

**Comment by aanoaa** [comment]
@10001if 옷을 골라주는 입장에서 의류를 제안해줄때, 가장 눈에 띄어야 하는게 무엇일까요?
의류코드? 색상? 신체 사이즈?

**Comment by yongbin** [comment]
참고로 현재 여성의류는 세트개념이 희박하기 때문에 여성의류는 검색결과가 아주 안좋습니다. 온라인대여에서도 여성의류는 추천하지 않기로 했기때문에 의류준비에서도 여성의류는 제외하고 남성의류만 표시하는것도 고려해볼 수 있습니다.

**Comment by aanoaa** [comment]
의류준비화면은 이미 나타내고 있는 정보가 많습니다.
의류검색 결과에 제안하게 될텐데, 제안된 의류의 어떤 정보를 어디에
어떻게 보여줘야 하는지 고민해야합니다.

3~5개 이상 보여주기 힘들지 않을까 생각됩니다.

이게 그림으로 나온다면 최고 일 것 같고요.
의류코드가 보여져야 한다거나,
의류코드+색상이 보여져야 한다거나

이런게 필요합니다.

**Comment by yongbin** [comment]
제가 @10001if 님과 의논해서 화면배치를 결정해야합니다.

**Comment by yongbin** [comment]
현재 화면 배치

![screen shot 2016-06-03 at 2 26 00 pm](https://cloud.githubusercontent.com/assets/52704/15769689/62ee85de-2998-11e6-828d-5e4564f2d3b3.png)

**Comment by aanoaa** [comment]
@yongbin 사용자 정보가 그대로 나타나니까 블러처리를 하던지 해주세요
그리고 앞으로도 이런건 계속해서 주의해주세요

**Comment by yongbin** [comment]
넵 블러처리했습니다. 주의하겠습니다.

**Comment by yongbin** [comment]
한만일대표님과 이야기기 나눈 내용을 나눠서 이슈등록하겠습니다.

**Comment by aanoaa** [comment]
이 이슈가 나눠져야 할정도로 뭔가 많은가요?
단순히 보여주는 차원이 아닌가요?

**Comment by yongbin** [comment]
2 x 3 가지 경우의 수가 나와서 한 이슈에 적기 너무 많을거 같아서(의류수선처럼) 이슈나눴습니다 보시고 너무 짜잘하다 싶으면 말씀해주세요

**Comment by aanoaa** [comment]
제안의류에 대한 이슈들이 많은데 요약해보면 이렇습니다.

- 이력에서 상하의만 보여준다
- pre_category 에 따라서 이력을 보여준다
- 이력에서 카테고리의 정렬
- 이력의 포맷변경

        2016-xx-xx
        J001 - 87
        P001 - 81

- 상하의 모두 대여가능한 이력만 표시
- 추천의류의 정렬은 색상, 대여횟수
- 추천의류의 포맷

        J001 - 87 검정
        P001 - 81 검정

- 신체치수영역의 크기를 20% 줄임
- 허벅지대신 허리를 강조
- 대여횟수표시

**Comment by aanoaa** [comment]
@yongbin 

- 마우스가 올려졌을때 나타나야 하는 바코드 번호는 무엇입니까?
- 질의후에 사이즈를 받아야 하는데 그때 받는 사이즈는 무엇입니까?

**Comment by yongbin** [comment]
> 마우스가 올려졌을때 나타나야 하는 바코드 번호는 무엇입니까?

https://github.com/opencloset/monitor/issues/115#issuecomment-223535896

**Comment by yongbin** [comment]
> 질의후에 사이즈를 받아야 하는데 그때 받는 사이즈는 무엇입니까?

`search_clothes` 핼퍼에 구현된 코드중에 

```perl
    my $guesser = OpenCloset::Size::Guess->new(
        'OpenCPU::RandomForest',
        gender    => $params{gender},
        height    => $params{height},
        weight    => $params{weight},
        _bust     => $params{bust},
        _waist    => $params{waist},
        _topbelly => $params{topbelly},
        _thigh    => $params{thigh},
        _arm      => $params{arm},
        _leg      => $params{leg},
    );
    $self->log->info(
        "guess params : " . encode_json( { user_id => $user_id, %params } ) );

    my $gender = $params{gender};
    my $guess  = $guesser->guess;
    return $self->error( 500, { str => "Guess failed: $guess->{reason}" } )
        unless $guess->{success};

    $self->log->info( "guess result size : " . encode_json($guess) );
```
에서 `$guess` 에 담겨있는 값들입니다.

```
$VAR1 = {
          'success' => 0,
          'bust' => '94.043',
          'thigh' => '58.4615',
          'topbelly' => '85.323',
          'waist' => '79.5196',
          'reason' => '',
          'arm' => '61.7423'
        };
```

**Comment by aanoaa** [comment]
핼퍼

**Comment by aanoaa** [comment]
진짜 저거 관심주기 싫은데 너무 보기 싫어서 계속 지적하게 됩니다.

**Comment by yongbin** [comment]
ㅠ ㅜ 수정했습니다.

**Comment by aanoaa** [comment]
보기싫은건지 어떤건지 너무 눈에 잘띄임
본문보다 오타가 강렬하게 인식됨

**Comment by yongbin** [comment]
> 제안의류에 대한 이슈들이 많은데 요약해보면 이렇습니다.

간략하게 적으셔서 약간 빠진거 같은게 보이지만 잘 이해하셨을꺼라고 생각합니다 진행하시다가 끊고 보여주실수 있으면 그때그때 확인하고 피드백 드리겠습니다.

**Comment by aanoaa** [comment]
몇일간 `ㅐ` 와 `ㅔ` 를 바꿔서 써보도록 하갰습니다

**Comment by aanoaa** [comment]
> 마우스가 올려졌을때 나타나야 하는 바코드 번호는 무엇입니까?
> 질의후에 사이즈를 받아야 하는데 그때 받는 사이즈는 무엇입니까?

1900 - 0001
입력된 신체사이즈에 대한 예측된 의류사이즈

**Comment by aanoaa** [comment]
지난 의류데여를 희망한다고 헸을떼,
데여가능 상테가 아니면 보이지도 않개 됩니다.

**Comment by aanoaa** [comment]
사용해본 테스터의 의견이 있으면 좋겠습니다.

**Comment by aanoaa** [comment]
queue 에서 데이터를 빼서 처리하는 스크립트를 데몬화하기 위한 ubic 설정입니다.
설정문제인지 STDOUT, STDERR 가 제대로 파일로 redirect 되지 않는 것 같습니다.

``` perl
#!/usr/bin/env perl
use strict;
use warnings;
use Ubic::Service::SimpleDaemon;

my $home    = '/home/aanoaa/repo/opencloset/monitor';
my $service = Ubic::Service::SimpleDaemon->new(
    bin => "$home/bin/suggestion_consumer.pl",

    # pidfile => $home,
    cwd    => $home,
    stdout => "$home/bin/consumer.stdout",
    stderr => "$home/bin/consumer.stderr",
    env    => {
        OPENCLOSET_MONITOR_EMAIL    => 'xxxxx',
        OPENCLOSET_MONITOR_PASSWORD => 'xxxxx'
    }
);
```

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2016-06-14 12-01-26](https://cloud.githubusercontent.com/assets/170528/16029921/d75e8fee-3227-11e6-88d2-fd9dd07c2645.png)

6번 탈의실에 사람이 있는데도 불구하고 6번탈의실을 선택할 수 있습니다.
어떤 상황에서 이런일이 벌어지는지 파악하고 수정해야 합니다.

**Comment by yongbin** [comment]
![screen_shot_2016-06-14_at_11_34_05_am](https://cloud.githubusercontent.com/assets/52704/16030793/d404f4f2-322f-11e6-8110-ac0cec11041d.png)

과거대여이력 5개, 추천의류 5개인 케이스

**Comment by aanoaa** [comment]
- 제안 사이즈 색상 다르게
- 마우스 올라갔을때, 기증자 이름 뜨게

**Comment by yongbin** [comment]
지금 추천의류항목이 5개 고정인데 조정해야하지 않을까요?

**Comment by aanoaa** [comment]
사용자들의 피드백을 통해서 부족하다고 하면 늘릴 것이고 많다고 하면 줄일겁니다.

**Comment by yongbin** [comment]
> 사용자들의 피드백을 통해서 부족하다고 하면 늘릴 것이고 많다고 하면 줄일겁니다.

지금 검색API에 색상이 없고 방문자중 처음방문하는 사람 비중이 높기때문에 기존에 이야기한것 처럼 10개에서 기존대여기록수를 뺀 수만큼씩 보여주는게 맞을것 같습니다(신규방문자라면 10개) 

https://github.com/opencloset/monitor/issues/115

> 10개(설정가능항목)에서 과거 대여기록 표시 수 (이 경우 3개) 를 뺀 나머지 자리 (이 경우 7개)에 과거 대여기록과 동일한 형식으로 검색 추천 의류를 표시합니다.

**Comment by aanoaa** [comment]
이 얘기가 계속해서 나오는데,
직접 진행하시기 바랍니다.

`region#selects` 액션의 `templates/partials/suggestion-clothes.html.ep` 템플릿 파일입니다.

js 는 건드릴 필요 없습니다.

**Comment by yongbin** [comment]
@aanoaa #120 PR 보냈습니다. 이쁘게 봐주세요~
