### ISSUE TITLE
온라인 대여화면에서 사용자의 신체치수도 나타냄

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#97]
현재 ~select 화면은 사용하지 않습니다. 하지만 이 화면을 온라인 용으로 사용하려고 합니다. 현재는 온라인 사용자의 정의를 22:00로 하고 있으므로, 22:00의 사용자만 본 화면에 나타나도록 요청드립니다. 현재 온라인 사용자의 사이즈를 일일이 노트에 적어 의류를 찾고 있다고 합니다. 때문에 이 화면으로 핸드폰을 통해 사이즈를 확인하려고 합니다.

**Comment by aanoaa** [comment]
라기보단 `/online` 에서 사용자의 필요한 신체치수를 나타내면 될 것 같습니다.

**Comment by MoDoLEE** [comment]
작업 시간이 많이 걸릴까봐 /select 에 요청 드렸는데,  어려운 작업이 아니시라면 /online에 작업해 주시면 더 좋을 것 같습니다.

**Comment by 10001if** [comment]
내일 찾아뵙고 다시 말씀드리도록 하겠습니다~ ^^

**Comment by aanoaa** [comment]
온라인 대여자의 모든 신체치수를 표시해주고 + 해당하는 치수의 평균도 보여줄 수 있는 버튼이 있으면 좋을 것 같습니다.
