### ISSUE TITLE
더나은 우클릭메뉴 제안과 정리가 필요한 탈의실 표시

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#98]
의류준비 화면은 거의 이슈들이 정리된 것 같습니다. 하지만 여전히 문제되는 것이 있는데요.

1. 의류준비상태 
2. 탈의실 3번에 들어감
3. 의류준비상태 (2번)
4. 탈의실 3번에 다시 들어감
5. 수선 혹은 포장 상태

하지만, 3번 탈의실에 들어가 있다가 -> 의류준비 상태로 바뀌는 경우, 3번 탈의실은 비어있는 상태가 됩니다.
때문에 의류준비 화면만 보면 탈의실 3번은 비어 있는 것 처럼 보입니다. (의류준비 상태에 3번 탈의실이 써 있긴 하지만, 그건 탈의실에 다시 넣을 때 사용하는 용도로는 적합하지만 탈의실 화면만 보고 있으면 탈의실에 사람이 있는지 여부는 알기가 힘듭니다.) 그래서 화면만 보고 다른 의류준비 상태인 사람을 3번에 넣거나 하는 일이 일어나고 있습니다. (실제 탈의실에는 사람이 있는데 화면만 보면 사람이 없다고 느끼기 때문입니다.)

그래서 수정을 요청드립니다.

3번 탈의실에서 있다가 의류 준비 화면으로 나가는 경우 탈의실이 비는게 아니라. 
한만일 36 2번째 의류 준비 중 이라는 문구가 남아 있으면 좋겠습니다. 의류준비 중인 사람의 정보는 기존과 동일하지만 탈의실이 비어있지 않고 사람이 들어 가 있음을 알려주기 때문에 실제 탈의실 현장과 모니터 화면의 정보가 일치하게 됩니다. 

그리고 현재는 3번 탈의실에 사람이 있는 경우 의류준비 중인 다른 사람을 3번 탈의실에 넣는 경우 새로 넣은 사람이 기존 사람을 덮는 구조가 됩니다. 하지만 3번 탈의실에 사람이 있는 경우 (탈의실에 넣거나 의류준비 중인 경우)에는 기존의 사람을 덮을 수 없도록 요청드립니다. 반드시 3번 탈의실의 사람이 나가는 경우에만 (탈의실이 실제로 비워지는 경우) 3번 탈의실에 의류준비 중인 사람을 넣을 수 있도록 하면 좋겠습니다. 

3번 탈의실이 비워지려면, 수선을 하거나 포장을 하거나 대여를 하지 않는 경우이므로 탈의실을 비우려면 3가지 중 한가지를 선택하여 진행하도록 하였으면 좋겠습니다. 

오늘 대여를 하다가 발견 한 부분인데 진작 요청드렸어야 했겠다는 생각이 들었습니다. 실수가 좀 있었던 걸로 들었거든요. 수정을 부탁드리겠습니다. ^^

**Comment by aanoaa** [comment]
탈의에서 -> 수선, 포장, 대여안함 으로 상태가 변경되었을때 탈의실내부 정리가 필요한데,
이를 위한 기능이 의류준비화면에 필요합니다.

예로, `정리` 라는 라벨이 보여지고 정리후에 클릭해서 `정리` 라는 라벨이 없어질 수 있도록

**Comment by aanoaa** [comment]
기능이 한개씩 한개씩 추가되어서, 지금은 좀 복잡합니다.

- active 상태 토글
- 우클릭 메뉴
- 수선완료 동기화
- 대쉬보드 동기화
- 포장으로 갈때 bestfit 입력
- 이름 눌러서 bestfit 토글
- 팬츠 길이 수선

주요하게 사용될 기능임이 분명하고 더이상의 복잡도를 늘리지 않기 위해서,
잘 모듈화 해서 진행해야 할 것 같습니다.

**Comment by aanoaa** [comment]
A 사용자가 1번 탈의실을 이용하고 있다면, A 사용자는 `탈의#1`, `수선`,
`포장` 으로만 이동할 수 있도록 하고, 나머지 의류준비 대기자는
사용가능한 탈의실(`탈의#n` .. `탈의#N`), `수선`, `포장` 으로만 변경할
수 있도록 하면 될 것 같습니다.

**Comment by aanoaa** [comment]
기능 시험하면서 발견한 버그

사용자 이름을 눌러서 베스트을 토글할때 다른 열려있는 브라우저와 sync 가 아니됨

**Comment by aanoaa** [comment]
정리 아이콘을 토글 가능하도록 해야 합니다.

그전에 우선 배포하도록 하겠습니다.

**Comment by aanoaa** [comment]
직접 기능에 대한 확인을 받았기 때문에 PR 없이 처리하였습니다.

**Comment by aanoaa** [comment]
@10001if 혹시나 내일 영업시간에 제대로 기능이 정상적으로 동작하지 않는다면
전화주세요.
바로 롤백할게요.

**Comment by aanoaa** [comment]
서버에서 `.opencloset.json` 파일이 엉뚱한 위치에 생성되고 있습니다.
꼭 이것때문은 아닌데 정상적으로 동작하고 있지 않기 때문에 지난 버전으로 롤백하였습니다.

**Comment by aanoaa** [comment]
파일의 절대경로를 설정해주고 적용 시켜 봤는데 제대로 동작하는 것 같습니다.

**Comment by aanoaa** [comment]
서버에서 `.opencloset.json` 이 제대로 써지지 않고 있습니다.
절대경로로 지정했는데도요.

환경변수를 바꿔준것이기 때문에 `reload` 가 아닌 `stop & start` 가 필요한게 아닐까 추측해봅니다.
워커가 여러개 떠있는것이 문제일 수도 있습니다.
추측일 뿐이고 가능성은 낮다고 봅니다.

**Comment by aanoaa** [comment]
로그를 많이 남겨서 왜 안되고 있는지 파악을 해봐야 합니다.

**Comment by aanoaa** [comment]
개발환경에서는 정상적으로 동작하는데, 서버에 띄우면 다르게 동작합니다.

**Comment by aanoaa** [comment]
오 localhost 에서 `morbo` 대신에 `hypnotoad` 로 띄우니까 문제가 재현됩니다.

**Comment by aanoaa** [comment]
배포하였습니다.
잘 되리라고 믿습니다.
