### ISSUE TITLE
의류준비에 대기목록을 나타냄

### ISSUE THREAD

**Issue by 10001if** [opencloset/monitor#99]
![2016-01-27 4 23 02](https://cloud.githubusercontent.com/assets/4696328/12606744/18bb54d6-c513-11e5-9e6d-2814af4dad11.png)
![2016-01-27 4 23 43](https://cloud.githubusercontent.com/assets/4696328/12606663/80edfe24-c512-11e5-9179-e0b8e59b7856.png)
의류준비 화면에 상태별로 인원을 표시해주는 화면이 추가되었으면 좋겠습니다.
요즘은 5층 인원이 유동적으로 운영이 되기 때문에 신체치수를 측정하는 인원이 따로 배치가 되지 않는 경우가 많이 있습니다. 따라서 리페어 화면에서 보이는 인원표시가 사용자 상단에 나타난다면 의류를 고르다가 바로 치수를 측정하러 갈 수 있을 것 같습니다. 우측 탈의실 화면은 그대로 유지되고, 좌측에 의류준비상태 인원 상단에 상태화면이 올라가면 될 것 같습니다. ^^

**Comment by aanoaa** [comment]
배포하였습니다.
